// 27/09/2026 — Daniel : expliquer dans « Comprendre la PawMap » que les
// positions sont floutées (~1 km) et que seul le Direct montre la position
// réelle ; + couleurs des profils et bulle double prix. 9 langues, fusionné dans translations.ts (même mécanisme que map590.ts).
import type { Lang } from "./translations";

type D = Record<string, string>;

export const PRIVACY2709: Record<Lang, D> = {
  fr: { priv2709_roles_t: "Couleurs des profils", priv2709_roles_b: "Le bouton « Profil » et le contour de la photo prennent la couleur du rôle : orange = propriétaire, bleu = gardien, vert = promeneur. Une personne qui a plusieurs rôles a un bouton bicolore ou tricolore, toujours dans cet ordre.", priv2709_duo_t: "Gardien + promeneur : deux prix", priv2709_duo_b: "Une seule bulle bleu et vert donne les deux tarifs : 🏠 la garde, 🚶 la promenade. Si vous filtrez un seul rôle, seul son prix s'affiche.", priv2709_title: "Votre position reste privée", priv2709_body: "Sur la carte, personne n'apparaît à son adresse exacte : pour votre sécurité et votre vie privée, chaque membre est placé dans un rayon d'environ 1 km autour de chez lui. Seul le mode Direct montre la position réelle, en temps réel, et uniquement pendant qu'il est activé." },
  en: { priv2709_roles_t: "Profile colours", priv2709_roles_b: "The “Profile” button and the photo border take the role's colour: orange = owner, blue = sitter, green = walker. Someone with several roles gets a two- or three-colour button, always in that order.", priv2709_duo_t: "Sitter + walker: two prices", priv2709_duo_b: "One blue-and-green bubble shows both rates: 🏠 sitting, 🚶 walking. If you filter a single role, only its price is shown.", priv2709_title: "Your location stays private", priv2709_body: "No one is shown at their exact address on the map: for your safety and privacy, every member is placed within about 1 km of their home. Only Live mode shows the real position, in real time, and only while it is switched on." },
  es: { priv2709_roles_t: "Colores de los perfiles", priv2709_roles_b: "El botón «Perfil» y el borde de la foto toman el color del rol: naranja = dueño, azul = cuidador, verde = paseador. Quien tiene varios roles tiene un botón de dos o tres colores, siempre en este orden.", priv2709_duo_t: "Cuidador + paseador: dos precios", priv2709_duo_b: "Una sola burbuja azul y verde muestra las dos tarifas: 🏠 el cuidado, 🚶 el paseo. Si filtras un solo rol, solo aparece su precio.", priv2709_title: "Tu ubicación sigue siendo privada", priv2709_body: "En el mapa nadie aparece en su dirección exacta: por tu seguridad y tu privacidad, cada miembro se sitúa en un radio de unos 1 km alrededor de su casa. Solo el modo Directo muestra la posición real, en tiempo real, y únicamente mientras está activado." },
  de: { priv2709_roles_t: "Farben der Profile", priv2709_roles_b: "Der Button „Profil“ und der Rand des Fotos haben die Farbe der Rolle: Orange = Halter, Blau = Sitter, Grün = Gassigeher. Wer mehrere Rollen hat, bekommt einen zwei- oder dreifarbigen Button, immer in dieser Reihenfolge.", priv2709_duo_t: "Sitter + Gassigeher: zwei Preise", priv2709_duo_b: "Eine blau-grüne Blase zeigt beide Preise: 🏠 Betreuung, 🚶 Gassigehen. Wenn du nur eine Rolle filterst, siehst du nur ihren Preis.", priv2709_title: "Dein Standort bleibt privat", priv2709_body: "Auf der Karte erscheint niemand an seiner genauen Adresse: Zu deiner Sicherheit und zum Schutz deiner Privatsphäre wird jedes Mitglied in einem Umkreis von etwa 1 km um sein Zuhause angezeigt. Nur der Live-Modus zeigt die echte Position, in Echtzeit, und nur solange er eingeschaltet ist." },
  it: { priv2709_roles_t: "Colori dei profili", priv2709_roles_b: "Il pulsante «Profilo» e il bordo della foto prendono il colore del ruolo: arancione = proprietario, blu = pet sitter, verde = dog walker. Chi ha più ruoli ha un pulsante a due o tre colori, sempre in quest'ordine.", priv2709_duo_t: "Pet sitter + dog walker: due prezzi", priv2709_duo_b: "Una sola bolla blu e verde mostra le due tariffe: 🏠 la custodia, 🚶 la passeggiata. Se filtri un solo ruolo, compare solo il suo prezzo.", priv2709_title: "La tua posizione resta privata", priv2709_body: "Sulla mappa nessuno appare al suo indirizzo esatto: per la tua sicurezza e la tua privacy, ogni membro è collocato in un raggio di circa 1 km da casa sua. Solo la modalità Diretta mostra la posizione reale, in tempo reale, e solo finché è attiva." },
  pt: { priv2709_roles_t: "Cores dos perfis", priv2709_roles_b: "O botão «Perfil» e o contorno da foto ficam com a cor do papel: laranja = dono, azul = cuidador, verde = passeador. Quem tem vários papéis tem um botão de duas ou três cores, sempre por esta ordem.", priv2709_duo_t: "Cuidador + passeador: dois preços", priv2709_duo_b: "Uma só bolha azul e verde mostra as duas tarifas: 🏠 o cuidado, 🚶 o passeio. Se filtrar um só papel, só aparece o seu preço.", priv2709_title: "A sua localização continua privada", priv2709_body: "No mapa, ninguém aparece na sua morada exata: pela sua segurança e privacidade, cada membro é colocado num raio de cerca de 1 km à volta de casa. Só o modo Direto mostra a posição real, em tempo real, e apenas enquanto está ativado." },
  ko: { priv2709_roles_t: "프로필 색상", priv2709_roles_b: "‘프로필’ 버튼과 사진 테두리는 역할 색을 따라요: 주황 = 보호자, 파랑 = 펫시터, 초록 = 산책 도우미. 역할이 여러 개인 사람은 항상 이 순서로 두세 가지 색 버튼이 돼요.", priv2709_duo_t: "펫시터 + 산책 도우미: 두 가지 가격", priv2709_duo_b: "파랑·초록 말풍선 하나에 두 요금이 표시돼요: 🏠 돌봄, 🚶 산책. 한 역할만 필터하면 그 가격만 보여요.", priv2709_title: "내 위치는 비공개로 보호돼요", priv2709_body: "지도에는 누구도 정확한 주소에 표시되지 않아요. 안전과 사생활 보호를 위해 모든 회원은 집에서 약 1km 반경 안에 표시돼요. 실제 위치는 라이브 모드를 켠 동안에만 실시간으로 보여요." },
  ja: { priv2709_roles_t: "プロフィールの色", priv2709_roles_b: "「プロフィール」ボタンと写真の縁は役割の色になります：オレンジ＝飼い主、青＝シッター、緑＝散歩代行。複数の役割を持つ人は、この順番で2色または3色のボタンになります。", priv2709_duo_t: "シッター＋散歩代行：2つの料金", priv2709_duo_b: "青と緑の吹き出し1つに2つの料金を表示：🏠 お世話、🚶 散歩。1つの役割だけで絞り込むと、その料金だけが表示されます。", priv2709_title: "あなたの位置はプライベートに守られます", priv2709_body: "地図上では、誰も正確な住所には表示されません。安全とプライバシーのため、各メンバーは自宅から約1kmの範囲内に表示されます。実際の位置がリアルタイムで表示されるのは、ライブモードをオンにしている間だけです。" },
  pl: { priv2709_roles_t: "Kolory profili", priv2709_roles_b: "Przycisk „Profil” i obramowanie zdjęcia mają kolor roli: pomarańczowy = właściciel, niebieski = opiekun, zielony = spacerowicz. Osoba z kilkoma rolami ma przycisk dwu- lub trzykolorowy, zawsze w tej kolejności.", priv2709_duo_t: "Opiekun + spacerowicz: dwie ceny", priv2709_duo_b: "Jeden niebiesko-zielony dymek pokazuje obie stawki: 🏠 opieka, 🚶 spacer. Jeśli filtrujesz jedną rolę, widać tylko jej cenę.", priv2709_title: "Twoja lokalizacja pozostaje prywatna", priv2709_body: "Na mapie nikt nie jest pokazany pod swoim dokładnym adresem: dla Twojego bezpieczeństwa i prywatności każdy członek jest umieszczony w promieniu około 1 km od domu. Tylko tryb Na żywo pokazuje prawdziwą pozycję, w czasie rzeczywistym, i tylko wtedy, gdy jest włączony." },
};
