// v547 — SEO programmatique « devenir pet sitter à <ville> ».
// Stratégie supply-first, Paris d'abord (objectif : premiers clients), puis
// USA, Pologne, Corée. Une page statique par ville/arrondissement, générée
// par le composant RecruitCityPage. Ajouter une ligne = une page indexable.

// v560 — moteur de croissance : +5 langues (es/de/it/pt/ja) et +57 villes.
export type RecruitLang = "fr" | "en" | "pl" | "ko" | "es" | "de" | "it" | "pt" | "ja";

export type RecruitCity = {
  slug: string;        // segment d'URL
  name: string;        // nom affiché (« Paris 11e », « Boulogne-Billancourt »)
  region: string;      // sous-titre (« Paris & Île-de-France »)
  lang: RecruitLang;
  /** Détail local pour rendre la page unique (quartiers, parcs, ambiance). */
  local: string;
  /** Fourchette de prix locale affichée dans la FAQ (déjà formatée). */
  dayRate: string;
  walkRate: string;
};

const PARIS_ARR: Array<[number, string]> = [
  [1, "Louvre, Palais-Royal et les Tuileries — beaucoup de résidents en appartement, peu d'espaces verts privés : la promenade est très demandée."],
  [2, "Sentier, Bourse et les passages couverts — un quartier de bureaux où les chiens attendent leurs maîtres toute la journée."],
  [3, "Le Marais nord, Arts-et-Métiers, le square du Temple — familles et jeunes actifs, forte densité de petits chiens."],
  [4, "Le Marais, l'île Saint-Louis et la place des Vosges — visites à domicile pour chats très fréquentes."],
  [5, "Quartier latin, Mouffetard, le Jardin des Plantes — étudiants disponibles et propriétaires qui voyagent souvent."],
  [6, "Saint-Germain-des-Prés, le Luxembourg — l'un des jardins les plus prisés des promeneurs de la capitale."],
  [7, "Invalides, Champ-de-Mars, Gros-Caillou — grands appartements, chiens de race, gardes de nuit régulières."],
  [8, "Champs-Élysées, parc Monceau, Madeleine — clientèle qui part souvent en week-end et cherche des gardes fiables."],
  [9, "Pigalle, Nouvelle-Athènes, les Grands Boulevards — jeunes couples, beaucoup de chats et de petits chiens."],
  [10, "Canal Saint-Martin, gares du Nord et de l'Est — voyageurs fréquents, gardes courtes autour des départs."],
  [11, "Oberkampf, Bastille, République — l'arrondissement le plus peuplé de Paris : la demande y est constante."],
  [12, "Bois de Vincennes, Bercy, Nation — le terrain de jeu idéal pour les promeneurs de grands chiens."],
  [13, "Butte-aux-Cailles, Bibliothèque, Olympiades — quartier familial en pleine croissance, peu de sitters installés."],
  [14, "Montparnasse, Alésia, parc Montsouris — retraités et familles qui privilégient la garde à domicile."],
  [15, "Vaugirard, Convention, parc André-Citroën — le plus grand arrondissement, des milliers de chiens déclarés."],
  [16, "Passy, Auteuil, le bois de Boulogne — demande élevée en gardes longues pendant les vacances scolaires."],
  [17, "Batignolles, Ternes, parc Martin-Luther-King — nouveaux résidents, beaucoup de chiots à sociabiliser."],
  [18, "Montmartre, Jules-Joffrin, la Goutte-d'Or — un tissu de voisinage où le bouche-à-oreille fait vite le plein."],
  [19, "Buttes-Chaumont, La Villette, le bassin — parcs immenses, promenades très demandées en semaine."],
  [20, "Belleville, Ménilmontant, Père-Lachaise — jeunes actifs en télétravail, gardes à la journée fréquentes."],
];

const PARIS_SUBURBS: Array<[string, string, string]> = [
  ["boulogne-billancourt", "Boulogne-Billancourt", "Aux portes du bois de Boulogne, familles nombreuses et chiens sportifs : les promeneurs y trouvent vite des habitués."],
  ["neuilly-sur-seine", "Neuilly-sur-Seine", "Grands appartements, animaux de race et gardes de nuit régulières : une clientèle exigeante et fidèle."],
  ["levallois-perret", "Levallois-Perret", "Une des villes les plus denses d'Europe : des centaines de chiens et très peu de sitters disponibles."],
  ["asnieres-sur-seine", "Asnières-sur-Seine", "Le premier pet sitter HoPetSit d'Île-de-France est ici : la ville où la communauté démarre."],
  ["clichy", "Clichy", "Jeunes actifs et familles, tout près des Batignolles : promenades et visites pour chats très demandées."],
  ["issy-les-moulineaux", "Issy-les-Moulineaux", "Quartiers résidentiels et bords de Seine : idéal pour des promenades régulières en semaine."],
  ["montreuil", "Montreuil", "La ville la plus peuplée de l'Est parisien : gardes à domicile et promenades au parc des Beaumonts."],
  ["vincennes", "Vincennes", "Le bois à deux pas : les propriétaires de grands chiens y cherchent des promeneurs endurants."],
  ["saint-denis", "Saint-Denis", "Peu de sitters installés, beaucoup de familles : une place à prendre pour les premiers inscrits."],
  ["ivry-sur-seine", "Ivry-sur-Seine", "Une ville en pleine transformation, proche de Paris 13 : la demande arrive plus vite que l'offre."],
  ["saint-maur-des-fosses", "Saint-Maur-des-Fossés", "Pavillons, jardins et boucle de la Marne : la garde à domicile y est la norme."],
  ["versailles", "Versailles", "Le parc du château et les grands jardins : promenades longues et gardes pendant les vacances."],
];

export const RECRUIT_CITIES: RecruitCity[] = [
  ...PARIS_ARR.map(([n, local]): RecruitCity => ({
    slug: `paris-${n}`,
    name: `Paris ${n}${n === 1 ? "er" : "e"}`,
    region: "Paris & Île-de-France",
    lang: "fr",
    local,
    dayRate: "20 à 30 €",
    walkRate: "12 à 20 €",
  })),
  ...PARIS_SUBURBS.map(([slug, name, local]): RecruitCity => ({
    slug, name, region: "Île-de-France", lang: "fr", local,
    dayRate: "18 à 28 €", walkRate: "12 à 18 €",
  })),
  { slug: "lyon", name: "Lyon", region: "Auvergne-Rhône-Alpes", lang: "fr", local: "Parc de la Tête d'Or, Croix-Rousse, Confluence : la deuxième ville de France pour les chiens en appartement.", dayRate: "18 à 26 €", walkRate: "10 à 16 €" },
  { slug: "marseille", name: "Marseille", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Calanques, Prado, Borély : promenades au soleil toute l'année et gardes estivales très demandées.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "bordeaux", name: "Bordeaux", region: "Nouvelle-Aquitaine", lang: "fr", local: "Chartrons, Bastide, parc Bordelais : jeunes familles et beaucoup de télétravail.", dayRate: "17 à 25 €", walkRate: "10 à 16 €" },
  { slug: "lille", name: "Lille", region: "Hauts-de-France", lang: "fr", local: "Vieux-Lille, Vauban, la Citadelle : étudiants disponibles et propriétaires qui partent souvent le week-end.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "toulouse", name: "Toulouse", region: "Occitanie", lang: "fr", local: "Saint-Cyprien, Compans, les berges de la Garonne : une ville jeune, très active, peu de sitters installés.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "nice", name: "Nice", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Promenade des Anglais, Cimiez, le port : gardes touristiques et clientèle internationale.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "nantes", name: "Nantes", region: "Pays de la Loire", lang: "fr", local: "Île de Nantes, Procé, bords de l'Erdre : familles et jeunes actifs, forte croissance.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  // ---------- USA (English) ----------
  { slug: "new-york", name: "New York", region: "New York, USA", lang: "en", local: "Apartment living from Brooklyn to the Upper West Side means dog walkers are booked every single weekday.", dayRate: "$40–70", walkRate: "$20–35" },
  { slug: "los-angeles", name: "Los Angeles", region: "California, USA", lang: "en", local: "From Silver Lake to Santa Monica, owners travel often and want a trusted sitter who knows the neighborhood.", dayRate: "$40–65", walkRate: "$20–30" },
  { slug: "dallas", name: "Dallas", region: "Texas, USA", lang: "en", local: "Uptown, Lakewood, Plano and Frisco: HoPetSit's first US community started here — early sitters get the regulars.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "houston", name: "Houston", region: "Texas, USA", lang: "en", local: "Sprawling neighborhoods, big yards and hot summers: overnight sitting and midday walks are in constant demand.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "miami", name: "Miami", region: "Florida, USA", lang: "en", local: "Brickell, Wynwood and Coral Gables: frequent travelers, small dogs and a year-round need for reliable sitters.", dayRate: "$35–60", walkRate: "$18–30" },
  { slug: "chicago", name: "Chicago", region: "Illinois, USA", lang: "en", local: "Lincoln Park, Wicker Park and the lakefront trail: walkers with regular clients are the norm here.", dayRate: "$35–60", walkRate: "$18–30" },
  { slug: "austin", name: "Austin", region: "Texas, USA", lang: "en", local: "One of the most dog-friendly cities in America — and one of the fastest-growing. Supply can't keep up.", dayRate: "$30–55", walkRate: "$15–25" },
  // ---------- Pologne (polski) ----------
  { slug: "warszawa", name: "Warszawa", region: "Mazowsze, Polska", lang: "pl", local: "Mokotów, Wola, Praga i Łazienki: coraz więcej psów w mieszkaniach, a opiekunów wciąż brakuje.", dayRate: "60–100 zł", walkRate: "30–50 zł" },
  { slug: "krakow", name: "Kraków", region: "Małopolska, Polska", lang: "pl", local: "Kazimierz, Podgórze, Błonia: studenci z wolnym czasem i właściciele, którzy często wyjeżdżają.", dayRate: "50–90 zł", walkRate: "25–45 zł" },
  { slug: "wroclaw", name: "Wrocław", region: "Dolny Śląsk, Polska", lang: "pl", local: "Nadodrze, Krzyki, Park Szczytnicki: młode rodziny i mnóstwo psów na spacerach nad Odrą.", dayRate: "50–90 zł", walkRate: "25–45 zł" },
  { slug: "poznan", name: "Poznań", region: "Wielkopolska, Polska", lang: "pl", local: "Jeżyce, Łazarz, Cytadela: aktywne miasto, w którym opieka dzienna nad psem jest codzienną potrzebą.", dayRate: "50–85 zł", walkRate: "25–40 zł" },
  { slug: "gdansk", name: "Gdańsk", region: "Pomorze, Polska", lang: "pl", local: "Wrzeszcz, Oliwa, plaże Trójmiasta: długie spacery nad morzem i opieka w sezonie letnim.", dayRate: "50–90 zł", walkRate: "25–45 zł" },
  // ---------- Corée (한국어) ----------
  { slug: "seoul", name: "서울", region: "대한민국", lang: "ko", local: "강남, 마포, 성수, 한강공원까지 — 1인 가구와 맞벌이 가정이 많아 평일 산책과 주말 돌봄 수요가 꾸준합니다.", dayRate: "3만~5만 원", walkRate: "1만 5천~2만 5천 원" },
  { slug: "busan", name: "부산", region: "대한민국", lang: "ko", local: "해운대, 광안리, 서면 — 바다를 따라 걷는 산책 코스와 여름 휴가철 돌봄 수요가 많습니다.", dayRate: "2만 5천~4만 5천 원", walkRate: "1만 5천~2만 원" },
  { slug: "incheon", name: "인천", region: "대한민국", lang: "ko", local: "송도, 청라, 부평 — 신도시 아파트 단지가 많아 반려견 돌봄 서비스가 빠르게 자리 잡고 있습니다.", dayRate: "2만 5천~4만 원", walkRate: "1만 5천~2만 원" },
  { slug: "daegu", name: "대구", region: "대한민국", lang: "ko", local: "수성구, 동성로, 앞산공원 — 여름이 더워 이른 아침과 저녁 산책 대행 수요가 높습니다.", dayRate: "2만 5천~4만 원", walkRate: "1만 5천~2만 원" },
  { slug: "daejeon", name: "대전", region: "대한민국", lang: "ko", local: "둔산, 유성, 갑천 산책로 — 연구단지의 맞벌이 가정이 많아 평일 돌봄이 꾸준합니다.", dayRate: "2만 5천~4만 원", walkRate: "1만 5천~2만 원" },
  // ---------- France (suite, v560) ----------
  { slug: "strasbourg", name: "Strasbourg", region: "Grand Est", lang: "fr", local: "Krutenau, Neudorf, parc de l'Orangerie : une ville cyclable où les promenades quotidiennes sont la norme.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "montpellier", name: "Montpellier", region: "Occitanie", lang: "fr", local: "Écusson, Port-Marianne, les plages à 20 minutes : étudiants disponibles toute l'année.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "rennes", name: "Rennes", region: "Bretagne", lang: "fr", local: "Thabor, Sainte-Anne, les Prairies Saint-Martin : une ville jeune où la garde entre voisins se professionnalise.", dayRate: "15 à 23 €", walkRate: "10 à 14 €" },
  { slug: "grenoble", name: "Grenoble", region: "Auvergne-Rhône-Alpes", lang: "fr", local: "Berriat, Île-Verte, la Bastille : chiens sportifs et propriétaires souvent en montagne le week-end.", dayRate: "15 à 23 €", walkRate: "10 à 14 €" },
  { slug: "rouen", name: "Rouen", region: "Normandie", lang: "fr", local: "Saint-Marc, Jardin des Plantes, les quais : familles et beaucoup de trajets vers Paris en semaine.", dayRate: "15 à 22 €", walkRate: "9 à 14 €" },
  { slug: "reims", name: "Reims", region: "Grand Est", lang: "fr", local: "Centre, Clairmarais, parc de Champagne : peu de sitters installés, une place à prendre.", dayRate: "15 à 22 €", walkRate: "9 à 14 €" },
  { slug: "toulon", name: "Toulon", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Mourillon, le Faron, les plages : gardes estivales et promenades au soleil.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "angers", name: "Angers", region: "Pays de la Loire", lang: "fr", local: "La Doutre, Saint-Serge, le lac de Maine : une ville verte, très familiale.", dayRate: "15 à 22 €", walkRate: "9 à 14 €" },
  { slug: "dijon", name: "Dijon", region: "Bourgogne-Franche-Comté", lang: "fr", local: "Centre historique, lac Kir, parc de la Colombière : propriétaires qui voyagent souvent.", dayRate: "15 à 22 €", walkRate: "9 à 14 €" },
  { slug: "nimes", name: "Nîmes", region: "Occitanie", lang: "fr", local: "Écusson, Jardins de la Fontaine, les garrigues : promenades matinales avant la chaleur.", dayRate: "15 à 22 €", walkRate: "9 à 14 €" },
  // ---------- USA (suite, v560) ----------
  { slug: "san-francisco", name: "San Francisco", region: "California, USA", lang: "en", local: "The Mission, Noe Valley, Golden Gate Park: more dogs than kids, and owners who commute or travel constantly.", dayRate: "$45–75", walkRate: "$25–40" },
  { slug: "seattle", name: "Seattle", region: "Washington, USA", lang: "en", local: "Capitol Hill, Ballard, Green Lake: one of the most dog-owning cities in the US, with rainy-day walks in demand.", dayRate: "$40–65", walkRate: "$20–35" },
  { slug: "boston", name: "Boston", region: "Massachusetts, USA", lang: "en", local: "Back Bay, South End, the Esplanade: dense neighborhoods where midday walkers keep regular clients for years.", dayRate: "$40–65", walkRate: "$20–35" },
  { slug: "denver", name: "Denver", region: "Colorado, USA", lang: "en", local: "Highlands, Wash Park, Cherry Creek: outdoor-loving owners who hike on weekends and need sitters at home.", dayRate: "$35–60", walkRate: "$18–30" },
  { slug: "atlanta", name: "Atlanta", region: "Georgia, USA", lang: "en", local: "Midtown, Decatur, the BeltLine: HoPetSit's first Georgia members joined here — early sitters get the regulars.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "phoenix", name: "Phoenix", region: "Arizona, USA", lang: "en", local: "Scottsdale, Tempe, Arcadia: early-morning walks in summer and snowbird owners who travel for months.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "san-diego", name: "San Diego", region: "California, USA", lang: "en", local: "North Park, La Jolla, Ocean Beach: beach walks year-round and a military community that deploys often.", dayRate: "$40–65", walkRate: "$20–30" },
  { slug: "philadelphia", name: "Philadelphia", region: "Pennsylvania, USA", lang: "en", local: "Fishtown, Rittenhouse, Fairmount Park: row-house living means daily walks are a must.", dayRate: "$35–60", walkRate: "$18–30" },
  // ---------- Pologne (suite, v560) ----------
  { slug: "lodz", name: "Łódź", region: "Łódzkie, Polska", lang: "pl", local: "Manufaktura, Piotrkowska, park Poniatowskiego: coraz więcej młodych właścicieli psów w centrum.", dayRate: "45–80 zł", walkRate: "25–40 zł" },
  { slug: "szczecin", name: "Szczecin", region: "Zachodniopomorskie, Polska", lang: "pl", local: "Śródmieście, Pogodno, Jasne Błonia: zielone miasto, w którym długie spacery są codziennością.", dayRate: "45–80 zł", walkRate: "25–40 zł" },
  { slug: "katowice", name: "Katowice", region: "Śląskie, Polska", lang: "pl", local: "Koszutka, Ligota, Dolina Trzech Stawów: rodziny pracujące na zmiany potrzebują opieki w ciągu dnia.", dayRate: "45–80 zł", walkRate: "25–40 zł" },
  // ---------- Espagne (español) ----------
  { slug: "madrid", name: "Madrid", region: "Comunidad de Madrid, España", lang: "es", local: "Chamberí, Malasaña, Retiro y Casa de Campo: pisos pequeños, muchos perros y dueños que viajan a menudo.", dayRate: "18 a 28 €", walkRate: "10 a 16 €" },
  { slug: "barcelona", name: "Barcelona", region: "Cataluña, España", lang: "es", local: "Gràcia, Eixample, Poblenou y la Barceloneta: paseos junto al mar y una comunidad internacional que sale mucho.", dayRate: "18 a 28 €", walkRate: "10 a 16 €" },
  { slug: "valencia", name: "Valencia", region: "Comunidad Valenciana, España", lang: "es", local: "Ruzafa, El Carmen, el Jardín del Turia: 9 km de parque para pasear y familias que buscan cuidadores de confianza.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "sevilla", name: "Sevilla", region: "Andalucía, España", lang: "es", local: "Triana, Nervión, el parque de María Luisa: paseos a primera hora en verano y cuidado en casa en vacaciones.", dayRate: "15 a 24 €", walkRate: "9 a 14 €" },
  { slug: "malaga", name: "Málaga", region: "Andalucía, España", lang: "es", local: "Centro, Teatinos, la Malagueta: residentes internacionales y dueños que viajan durante todo el año.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "alicante", name: "Alicante", region: "Comunidad Valenciana, España", lang: "es", local: "Playa de San Juan, Centro, y toda la Marina Alta hasta Dénia y Jávea: los primeros miembros de HoPetSit en España están aquí.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "bilbao", name: "Bilbao", region: "País Vasco, España", lang: "es", local: "Abando, Indautxu, el parque de Doña Casilda: una ciudad compacta donde los paseadores fidelizan rápido.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "zaragoza", name: "Zaragoza", region: "Aragón, España", lang: "es", local: "Centro, Delicias, el parque Grande: pocos cuidadores instalados y mucha demanda en puentes y vacaciones.", dayRate: "15 a 23 €", walkRate: "9 a 14 €" },
  // ---------- Allemagne (Deutsch) ----------
  { slug: "berlin", name: "Berlin", region: "Berlin, Deutschland", lang: "de", local: "Prenzlauer Berg, Kreuzberg, Tempelhofer Feld: eine der hundefreundlichsten Städte Europas — und ständig neue Halter.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "muenchen", name: "München", region: "Bayern, Deutschland", lang: "de", local: "Schwabing, Haidhausen, Englischer Garten: anspruchsvolle Halter, die zuverlässige Betreuung gut bezahlen.", dayRate: "22 bis 35 €", walkRate: "14 bis 20 €" },
  { slug: "hamburg", name: "Hamburg", region: "Hamburg, Deutschland", lang: "de", local: "Eimsbüttel, Ottensen, Alster und Elbstrand: lange Spaziergänge bei jedem Wetter sind hier Alltag.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "koeln", name: "Köln", region: "Nordrhein-Westfalen, Deutschland", lang: "de", local: "Ehrenfeld, Südstadt, Stadtwald: junge Familien und viele Pendler, die tagsüber Betreuung brauchen.", dayRate: "18 bis 28 €", walkRate: "12 bis 17 €" },
  { slug: "frankfurt", name: "Frankfurt am Main", region: "Hessen, Deutschland", lang: "de", local: "Bornheim, Sachsenhausen, Stadtwald: Geschäftsreisende und Halter mit langen Arbeitstagen.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "stuttgart", name: "Stuttgart", region: "Baden-Württemberg, Deutschland", lang: "de", local: "West, Vaihingen, Rosensteinpark: Hügel, Wälder und Halter, die am Wochenende gern wandern.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  // ---------- Italie (italiano) ----------
  { slug: "roma", name: "Roma", region: "Lazio, Italia", lang: "it", local: "Prati, Trastevere, Villa Borghese e Villa Pamphili: tantissimi cani in appartamento e proprietari spesso in viaggio.", dayRate: "18 a 28 €", walkRate: "10 a 16 €" },
  { slug: "milano", name: "Milano", region: "Lombardia, Italia", lang: "it", local: "Isola, Porta Romana, Parco Sempione: giornate lavorative lunghe e una forte domanda di passeggiate a mezzogiorno.", dayRate: "20 a 30 €", walkRate: "12 a 18 €" },
  { slug: "torino", name: "Torino", region: "Piemonte, Italia", lang: "it", local: "San Salvario, Crocetta, il Valentino: una città verde dove la passeggiata quotidiana è un'abitudine.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "napoli", name: "Napoli", region: "Campania, Italia", lang: "it", local: "Vomero, Chiaia, Posillipo: pochi pet sitter organizzati e molte famiglie che cercano una persona di fiducia.", dayRate: "15 a 23 €", walkRate: "9 a 14 €" },
  { slug: "firenze", name: "Firenze", region: "Toscana, Italia", lang: "it", local: "Santo Spirito, Campo di Marte, le Cascine: residenti internazionali e proprietari che viaggiano spesso.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "bologna", name: "Bologna", region: "Emilia-Romagna, Italia", lang: "it", local: "Bolognina, Santo Stefano, i Giardini Margherita: studenti disponibili e famiglie con cani di taglia media.", dayRate: "16 a 24 €", walkRate: "10 a 15 €" },
  // ---------- Portugal (português) ----------
  { slug: "lisboa", name: "Lisboa", region: "Lisboa, Portugal", lang: "pt", local: "Campo de Ourique, Alvalade, Monsanto: uma comunidade internacional que viaja muito e procura cuidadores de confiança.", dayRate: "15 a 25 €", walkRate: "8 a 14 €" },
  { slug: "porto", name: "Porto", region: "Porto, Portugal", lang: "pt", local: "Foz, Cedofeita, Parque da Cidade: passeios junto ao rio e ao mar, famílias que trabalham fora todo o dia.", dayRate: "14 a 22 €", walkRate: "8 a 13 €" },
  { slug: "braga", name: "Braga", region: "Braga, Portugal", lang: "pt", local: "Centro, São Vítor, Bom Jesus: uma cidade jovem, com estudantes disponíveis e poucos cuidadores instalados.", dayRate: "12 a 20 €", walkRate: "7 a 12 €" },
  { slug: "coimbra", name: "Coimbra", region: "Coimbra, Portugal", lang: "pt", local: "Baixa, Celas, o Choupal: estudantes com tempo livre e proprietários que viajam nas férias.", dayRate: "12 a 20 €", walkRate: "7 a 12 €" },
  // ---------- Japon (日本語) ----------
  { slug: "tokyo", name: "東京", region: "日本", lang: "ja", local: "世田谷、目黒、代々木公園周辺 — 単身世帯と共働き家庭が多く、平日の散歩代行と留守中のお世話の需要が安定しています。", dayRate: "4,000〜7,000円", walkRate: "2,000〜3,500円" },
  { slug: "osaka", name: "大阪", region: "日本", lang: "ja", local: "北区、天王寺、鶴見緑地 — 小型犬が多く、旅行や出張の際の預かりニーズが高いエリアです。", dayRate: "3,500〜6,000円", walkRate: "1,800〜3,000円" },
  { slug: "nagoya", name: "名古屋", region: "日本", lang: "ja", local: "千種、名東、鶴舞公園 — 郊外に一戸建てが多く、自宅でのお世話や長めの散歩が好まれます。", dayRate: "3,500〜6,000円", walkRate: "1,800〜3,000円" },
  { slug: "fukuoka", name: "福岡", region: "日本", lang: "ja", local: "中央区、早良区、大濠公園 — 住みやすさで人気の街、若い飼い主が多くシッターはまだ少数です。", dayRate: "3,000〜5,500円", walkRate: "1,500〜2,800円" },
  // ---------- v560 (2) — Paris d'abord, toute la France, l'Europe (fr/de/it/es/pt/pl + anglais) et les USA ----------
  { slug: "nanterre", name: "Nanterre", region: "Île-de-France", lang: "fr", local: "Préfecture des Hauts-de-Seine, parc André-Malraux : beaucoup de familles et de jeunes actifs qui travaillent à La Défense.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "courbevoie", name: "Courbevoie", region: "Île-de-France", lang: "fr", local: "La Défense et le parc de Bécon : des pet sitters HoPetSit y sont déjà inscrits, la demande suit.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "puteaux", name: "Puteaux", region: "Île-de-France", lang: "fr", local: "Entre la Seine et La Défense : chiens d'appartement et propriétaires aux horaires de bureau.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "suresnes", name: "Suresnes", region: "Île-de-France", lang: "fr", local: "Mont-Valérien, bords de Seine : promenades vallonnées et gardes de week-end.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "rueil-malmaison", name: "Rueil-Malmaison", region: "Île-de-France", lang: "fr", local: "Parc de Bois-Préau, bords de Seine : grandes maisons, chiens de famille, gardes pendant les vacances.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "colombes", name: "Colombes", region: "Île-de-France", lang: "fr", local: "Ville dense et familiale, proche d'Asnières où la communauté HoPetSit a démarré.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "argenteuil", name: "Argenteuil", region: "Île-de-France", lang: "fr", local: "La plus grande ville du Val-d'Oise : très peu de sitters installés, une demande qui attend.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "saint-germain-en-laye", name: "Saint-Germain-en-Laye", region: "Île-de-France", lang: "fr", local: "La forêt à deux pas : promeneurs endurants et gardes longues très demandées.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "meudon", name: "Meudon", region: "Île-de-France", lang: "fr", local: "Forêt de Meudon, observatoire : promenades nature et familles avec plusieurs animaux.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "sevres", name: "Sèvres", region: "Île-de-France", lang: "fr", local: "Parc de Saint-Cloud tout proche : promenades quotidiennes et visites pour chats.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "vanves", name: "Vanves", region: "Île-de-France", lang: "fr", local: "Petite ville collée à Paris 15 : chats en appartement et propriétaires qui voyagent.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "malakoff", name: "Malakoff", region: "Île-de-France", lang: "fr", local: "Aux portes de Paris 14, jeunes ménages et animaux en appartement : visites à domicile fréquentes.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "montrouge", name: "Montrouge", region: "Île-de-France", lang: "fr", local: "L'une des villes les plus denses de France : la demande de promenades est constante.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "gentilly", name: "Gentilly", region: "Île-de-France", lang: "fr", local: "Entre Paris 13 et le Kremlin-Bicêtre : petits chiens, visites pour chats, horaires de bureau.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "le-kremlin-bicetre", name: "Le Kremlin-Bicêtre", region: "Île-de-France", lang: "fr", local: "Hôpital, universités : soignants et étudiants aux horaires décalés, gardes de jour comme de nuit.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "charenton-le-pont", name: "Charenton-le-Pont", region: "Île-de-France", lang: "fr", local: "Bois de Vincennes en voisin : promenades longues et propriétaires exigeants.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "saint-mande", name: "Saint-Mandé", region: "Île-de-France", lang: "fr", local: "Le bois de Vincennes à la porte : le paradis des promeneurs de grands chiens.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "nogent-sur-marne", name: "Nogent-sur-Marne", region: "Île-de-France", lang: "fr", local: "Bords de Marne, pavillons et jardins : garde à domicile pendant les vacances.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "le-perreux-sur-marne", name: "Le Perreux-sur-Marne", region: "Île-de-France", lang: "fr", local: "Ville résidentielle et familiale : chiens de maison, promenades sur les quais de Marne.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "fontenay-sous-bois", name: "Fontenay-sous-Bois", region: "Île-de-France", lang: "fr", local: "Entre bois de Vincennes et centre-ville : beaucoup de chiens, peu de sitters.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "champigny-sur-marne", name: "Champigny-sur-Marne", region: "Île-de-France", lang: "fr", local: "Grande ville de banlieue est : familles nombreuses et animaux de compagnie très présents.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "creteil", name: "Créteil", region: "Île-de-France", lang: "fr", local: "Préfecture du Val-de-Marne, lac de Créteil : promenades au bord de l'eau et gardes de semaine.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "maisons-alfort", name: "Maisons-Alfort", region: "Île-de-France", lang: "fr", local: "L'école vétérinaire est ici : étudiants passionnés d'animaux disponibles pour garder.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "vitry-sur-seine", name: "Vitry-sur-Seine", region: "Île-de-France", lang: "fr", local: "La ville la plus peuplée du Val-de-Marne : une demande importante et presque aucun sitter.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "antony", name: "Antony", region: "Île-de-France", lang: "fr", local: "Parc de Sceaux, pavillons : gardes à domicile et promenades au parc.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "sceaux", name: "Sceaux", region: "Île-de-France", lang: "fr", local: "Le parc de Sceaux : promenades élégantes et propriétaires qui partent souvent.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "pantin", name: "Pantin", region: "Île-de-France", lang: "fr", local: "Canal de l'Ourcq, nouveaux quartiers : jeunes actifs, chiens et chats en appartement.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "aubervilliers", name: "Aubervilliers", region: "Île-de-France", lang: "fr", local: "Ville jeune en pleine transformation : la demande arrive avant l'offre de sitters.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "saint-ouen-sur-seine", name: "Saint-Ouen-sur-Seine", region: "Île-de-France", lang: "fr", local: "Puces, nouveaux quartiers, Grand Parc : propriétaires nouvellement installés.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "bagnolet", name: "Bagnolet", region: "Île-de-France", lang: "fr", local: "Aux portes de Paris 20 : petits chiens et chats, visites à domicile en semaine.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "les-lilas", name: "Les Lilas", region: "Île-de-France", lang: "fr", local: "Petite ville-village aux portes de Paris : le bouche-à-oreille fait vite le tour.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "clamart", name: "Clamart", region: "Île-de-France", lang: "fr", local: "Bois de Clamart : promenades en forêt et familles avec jardin.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "chatillon", name: "Châtillon", region: "Île-de-France", lang: "fr", local: "Résidentielle et calme, proche de Paris 14 : gardes de week-end et visites.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "enghien-les-bains", name: "Enghien-les-Bains", region: "Île-de-France", lang: "fr", local: "Le lac, le casino, les villas : gardes de nuit et clientèle fidèle.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "sarcelles", name: "Sarcelles", region: "Île-de-France", lang: "fr", local: "Grande ville du Val-d'Oise sans offre de garde structurée : place à prendre.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "evry-courcouronnes", name: "Évry-Courcouronnes", region: "Île-de-France", lang: "fr", local: "Préfecture de l'Essonne : familles, pavillons, gardes pendant les vacances scolaires.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "massy", name: "Massy", region: "Île-de-France", lang: "fr", local: "Gare TGV, quartiers neufs : propriétaires qui voyagent, gardes courtes et régulières.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "cergy", name: "Cergy", region: "Île-de-France", lang: "fr", local: "Base de loisirs, étudiants : promeneurs disponibles et familles nombreuses.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "marne-la-vallee", name: "Marne-la-Vallée", region: "Île-de-France", lang: "fr", local: "Val d'Europe, Disneyland : salariés aux horaires décalés et chiens en pavillon.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "fontainebleau", name: "Fontainebleau", region: "Île-de-France", lang: "fr", local: "La forêt la plus célèbre d'Île-de-France : promeneurs sportifs et gardes de week-end.", dayRate: "18 à 28 €", walkRate: "12 à 18 €" },
  { slug: "le-havre", name: "Le Havre", region: "Normandie", lang: "fr", local: "Plage, forêt de Montgeon : promenades au grand air toute l'année.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "saint-etienne", name: "Saint-Étienne", region: "Auvergne-Rhône-Alpes", lang: "fr", local: "Ville étudiante et familiale, loyers doux : beaucoup d'animaux, peu de sitters.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "aix-en-provence", name: "Aix-en-Provence", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Cours Mirabeau, étudiants et familles aisées : gardes pendant les vacances et promenades.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "brest", name: "Brest", region: "Bretagne", lang: "fr", local: "Bord de mer, ville jeune : promenades sur la côte et gardes de marins en mission.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "tours", name: "Tours", region: "Centre-Val de Loire", lang: "fr", local: "Bords de Loire, étudiants : promeneurs disponibles et familles.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "clermont-ferrand", name: "Clermont-Ferrand", region: "Auvergne-Rhône-Alpes", lang: "fr", local: "Volcans à deux pas : chiens sportifs, propriétaires randonneurs.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "metz", name: "Metz", region: "Grand Est", lang: "fr", local: "Plan d'eau, Pompidou-Metz : ville verte et familiale.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "nancy", name: "Nancy", region: "Grand Est", lang: "fr", local: "Place Stanislas, pépinière : étudiants et jeunes couples avec chats.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "perpignan", name: "Perpignan", region: "Occitanie", lang: "fr", local: "Soleil et proximité de la mer : promenades matinales et gardes estivales.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "caen", name: "Caen", region: "Normandie", lang: "fr", local: "Prairie, Orne : ville étudiante avec beaucoup de familles alentour.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "orleans", name: "Orléans", region: "Centre-Val de Loire", lang: "fr", local: "Bords de Loire, forêt d'Orléans : promeneurs de grands chiens recherchés.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "mulhouse", name: "Mulhouse", region: "Grand Est", lang: "fr", local: "Ville frontalière et familiale : gardes à domicile pendant les congés.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "limoges", name: "Limoges", region: "Nouvelle-Aquitaine", lang: "fr", local: "Ville verte et calme : garde à domicile, animaux de maison.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "avignon", name: "Avignon", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Remparts, festival : propriétaires absents l'été, gardes très demandées.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "annecy", name: "Annecy", region: "Auvergne-Rhône-Alpes", lang: "fr", local: "Le lac, les montagnes : chiens sportifs et week-ends en randonnée.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "biarritz", name: "Biarritz", region: "Nouvelle-Aquitaine", lang: "fr", local: "Océan, surf : gardes de vacances et promenades sur la plage hors saison.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "la-rochelle", name: "La Rochelle", region: "Nouvelle-Aquitaine", lang: "fr", local: "Vieux-Port, île de Ré : touristes et résidents qui voyagent.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "cannes", name: "Cannes", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Croisette, festivals : clientèle internationale, gardes de courte durée.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "antibes", name: "Antibes", region: "Provence-Alpes-Côte d'Azur", lang: "fr", local: "Juan-les-Pins, Sophia Antipolis : familles et cadres expatriés.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "villeurbanne", name: "Villeurbanne", region: "Auvergne-Rhône-Alpes", lang: "fr", local: "Collée à Lyon, très étudiante : promeneurs disponibles en semaine.", dayRate: "16 à 25 €", walkRate: "10 à 15 €" },
  { slug: "bruxelles", name: "Bruxelles", region: "Belgique", lang: "fr", local: "Ixelles, Uccle, le bois de la Cambre : expatriés européens qui voyagent sans cesse.", dayRate: "20 à 30 €", walkRate: "12 à 18 €" },
  { slug: "liege", name: "Liège", region: "Belgique", lang: "fr", local: "Outremeuse, Guillemins : ville étudiante, gardes de week-end.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "namur", name: "Namur", region: "Belgique", lang: "fr", local: "Citadelle, bords de Meuse : familles et promenades nature.", dayRate: "16 à 24 €", walkRate: "10 à 15 €" },
  { slug: "charleroi", name: "Charleroi", region: "Belgique", lang: "fr", local: "Grande ville sans offre structurée : les premiers sitters prennent tout.", dayRate: "15 à 22 €", walkRate: "9 à 14 €" },
  { slug: "geneve", name: "Genève", region: "Suisse", lang: "fr", local: "Eaux-Vives, Carouge, organisations internationales : budgets élevés, exigences élevées.", dayRate: "40 à 60 CHF", walkRate: "20 à 30 CHF" },
  { slug: "lausanne", name: "Lausanne", region: "Suisse", lang: "fr", local: "Ouchy, le lac, l'EPFL : étudiants disponibles, propriétaires qui voyagent.", dayRate: "35 à 55 CHF", walkRate: "18 à 28 CHF" },
  { slug: "luxembourg", name: "Luxembourg", region: "Luxembourg", lang: "fr", local: "Kirchberg, Limpertsberg : frontaliers et fonctionnaires européens aux longues journées.", dayRate: "25 à 35 €", walkRate: "15 à 22 €" },
  { slug: "monaco", name: "Monaco", region: "Monaco", lang: "fr", local: "Petits chiens, longs déplacements : gardes de luxe et promenades sur le Rocher.", dayRate: "30 à 50 €", walkRate: "18 à 30 €" },
  { slug: "duesseldorf", name: "Düsseldorf", region: "Nordrhein-Westfalen, Deutschland", lang: "de", local: "Rheinufer, Flingern, Oberkassel: viele Berufspendler, Betreuung unter der Woche gefragt.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "leipzig", name: "Leipzig", region: "Sachsen, Deutschland", lang: "de", local: "Clara-Zetkin-Park, Südvorstadt: junge Stadt mit vielen Hunden und wenigen Sittern.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "dresden", name: "Dresden", region: "Sachsen, Deutschland", lang: "de", local: "Elbwiesen, Neustadt: lange Spaziergänge am Fluss, Familien mit Garten.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "hannover", name: "Hannover", region: "Niedersachsen, Deutschland", lang: "de", local: "Eilenriede, Maschsee: der größte Stadtwald Europas direkt vor der Tür.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "nuernberg", name: "Nürnberg", region: "Bayern, Deutschland", lang: "de", local: "Altstadt, Wöhrder See: Familien und Pendler, Betreuung in den Ferien.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "bremen", name: "Bremen", region: "Bremen, Deutschland", lang: "de", local: "Bürgerpark, Viertel: hundefreundliche Stadt mit Bedarf an Gassigehern.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "essen", name: "Essen", region: "Nordrhein-Westfalen, Deutschland", lang: "de", local: "Grugapark, Baldeneysee: Ruhrgebiet mit Schichtarbeit und Betreuung tagsüber.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "wien", name: "Wien", region: "Wien, Österreich", lang: "de", local: "Prater, Donauinsel, Hundezonen in jedem Bezirk: eine der hundefreundlichsten Hauptstädte.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "graz", name: "Graz", region: "Steiermark, Österreich", lang: "de", local: "Schlossberg, Murufer: Studenten mit Zeit und Familien mit Hunden.", dayRate: "20 bis 30 €", walkRate: "12 bis 18 €" },
  { slug: "zuerich", name: "Zürich", region: "Zürich, Schweiz", lang: "de", local: "Seefeld, Wiedikon, Uetliberg: hohe Ansprüche, hohe Preise, treue Kundschaft.", dayRate: "35 bis 55 CHF", walkRate: "18 bis 28 CHF" },
  { slug: "bern", name: "Bern", region: "Bern, Schweiz", lang: "de", local: "Aare, Gurten: Spaziergänge am Fluss und Betreuung während der Ferien.", dayRate: "35 bis 55 CHF", walkRate: "18 bis 28 CHF" },
  { slug: "basel", name: "Basel", region: "Basel-Stadt, Schweiz", lang: "de", local: "Rheinufer, Grenzgänger: Betreuung unter der Woche für Berufstätige.", dayRate: "35 bis 55 CHF", walkRate: "18 bis 28 CHF" },
  { slug: "venezia", name: "Venezia", region: "Veneto, Italia", lang: "it", local: "Mestre, Lido, il Cannaregio: proprietari che viaggiano e cani abituati alle calli.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "genova", name: "Genova", region: "Liguria, Italia", lang: "it", local: "Albaro, Nervi, il porto antico: passeggiate sul mare tutto l'anno.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "verona", name: "Verona", region: "Veneto, Italia", lang: "it", local: "Borgo Trento, le Torricelle: famiglie e coppie giovani con cani di taglia media.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "palermo", name: "Palermo", region: "Sicilia, Italia", lang: "it", local: "Mondello, Libertà: pochissimi pet sitter organizzati, tanta domanda estiva.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "bari", name: "Bari", region: "Puglia, Italia", lang: "it", local: "Lungomare, Poggiofranco: passeggiate al mare e custodia nei ponti festivi.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "padova", name: "Padova", region: "Veneto, Italia", lang: "it", local: "Prato della Valle, città universitaria: studenti disponibili in settimana.", dayRate: "16 a 25 €", walkRate: "10 a 15 €" },
  { slug: "palma", name: "Palma", region: "Islas Baleares, España", lang: "es", local: "Santa Catalina, Portixol: residentes internacionales y dueños que viajan en temporada.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "murcia", name: "Murcia", region: "Región de Murcia, España", lang: "es", local: "Huerta, centro: pocos cuidadores y muchas familias con perro.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "las-palmas", name: "Las Palmas de Gran Canaria", region: "Canarias, España", lang: "es", local: "Las Canteras, Vegueta: paseos junto al mar todo el año.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "granada", name: "Granada", region: "Andalucía, España", lang: "es", local: "Albaicín, Realejo: ciudad universitaria con estudiantes disponibles.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "marbella", name: "Marbella", region: "Andalucía, España", lang: "es", local: "Puerto Banús, San Pedro: residentes extranjeros y cuidados de larga duración.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "valladolid", name: "Valladolid", region: "Castilla y León, España", lang: "es", local: "Campo Grande, Parquesol: familias y perros de casa.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "vigo", name: "Vigo", region: "Galicia, España", lang: "es", local: "Samil, Castrelos: paseos con lluvia o sol, dueños que trabajan fuera.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "ibiza", name: "Ibiza", region: "Islas Baleares, España", lang: "es", local: "Temporada larga, dueños ausentes: cuidados de semanas enteras.", dayRate: "16 a 25 €", walkRate: "9 a 15 €" },
  { slug: "faro", name: "Faro", region: "Algarve, Portugal", lang: "pt", local: "Ria Formosa, expatriados: cuidados longos na época alta.", dayRate: "12 a 20 €", walkRate: "7 a 12 €" },
  { slug: "funchal", name: "Funchal", region: "Madeira, Portugal", lang: "pt", local: "Clima ameno o ano inteiro: passeios diários e famílias que viajam.", dayRate: "12 a 20 €", walkRate: "7 a 12 €" },
  { slug: "setubal", name: "Setúbal", region: "Setúbal, Portugal", lang: "pt", local: "Arrábida, praias: passeios ao ar livre e cuidado ao domicílio.", dayRate: "12 a 20 €", walkRate: "7 a 12 €" },
  { slug: "lublin", name: "Lublin", region: "Lubelskie, Polska", lang: "pl", local: "Stare Miasto, Ogród Saski: miasto studenckie, opiekunów wciąż brakuje.", dayRate: "45–80 zł", walkRate: "25–40 zł" },
  { slug: "bydgoszcz", name: "Bydgoszcz", region: "Kujawsko-Pomorskie, Polska", lang: "pl", local: "Wyspa Młyńska, Myślęcinek: długie spacery i opieka w wakacje.", dayRate: "45–80 zł", walkRate: "25–40 zł" },
  { slug: "bialystok", name: "Białystok", region: "Podlaskie, Polska", lang: "pl", local: "Park Branickich, Las Zwierzyniecki: rodziny z psami, mało opiekunów.", dayRate: "45–80 zł", walkRate: "25–40 zł" },
  { slug: "london", name: "London", region: "United Kingdom", lang: "en", local: "Hampstead Heath, Battersea, Richmond Park: millions of dogs, long commutes and a constant need for weekday walkers.", dayRate: "£30–50", walkRate: "£15–25" },
  { slug: "manchester", name: "Manchester", region: "United Kingdom", lang: "en", local: "Didsbury, Chorlton, Heaton Park: a young, dog-loving city where regular walkers are in short supply.", dayRate: "£25–40", walkRate: "£12–20" },
  { slug: "birmingham", name: "Birmingham", region: "United Kingdom", lang: "en", local: "Moseley, Sutton Park, Cannon Hill: big families, big gardens, holiday sitting in demand.", dayRate: "£25–40", walkRate: "£12–20" },
  { slug: "edinburgh", name: "Edinburgh", region: "United Kingdom", lang: "en", local: "Holyrood Park, Portobello beach, the Meadows: walkers with regular clients thrive here.", dayRate: "£25–45", walkRate: "£12–22" },
  { slug: "glasgow", name: "Glasgow", region: "United Kingdom", lang: "en", local: "West End, Pollok Park, Kelvingrove: friendly city, plenty of dogs, few professional sitters.", dayRate: "£25–40", walkRate: "£12–20" },
  { slug: "bristol", name: "Bristol", region: "United Kingdom", lang: "en", local: "Clifton, Ashton Court, the Downs: outdoorsy owners who travel at weekends.", dayRate: "£25–40", walkRate: "£12–20" },
  { slug: "leeds", name: "Leeds", region: "United Kingdom", lang: "en", local: "Roundhay Park, Headingley: students available on weekdays, families needing holiday cover.", dayRate: "£22–38", walkRate: "£12–18" },
  { slug: "liverpool", name: "Liverpool", region: "United Kingdom", lang: "en", local: "Sefton Park, Crosby beach: long beach walks and holiday sitting.", dayRate: "£22–38", walkRate: "£12–18" },
  { slug: "dublin", name: "Dublin", region: "Ireland", lang: "en", local: "Phoenix Park, Sandymount strand: expats and tech workers with long office days.", dayRate: "€25–40", walkRate: "€15–22" },
  { slug: "cork", name: "Cork", region: "Ireland", lang: "en", local: "Fitzgerald Park, the Lee walkways: families and students, few sitters.", dayRate: "€22–35", walkRate: "€12–20" },
  { slug: "amsterdam", name: "Amsterdam", region: "Netherlands", lang: "en", local: "Vondelpark, De Pijp, Amsterdamse Bos: bikes, canals and dogs everywhere, owners who travel.", dayRate: "€25–40", walkRate: "€15–22" },
  { slug: "rotterdam", name: "Rotterdam", region: "Netherlands", lang: "en", local: "Kralingse Bos, Blijdorp: a working city that needs midday walks.", dayRate: "€22–35", walkRate: "€12–20" },
  { slug: "utrecht", name: "Utrecht", region: "Netherlands", lang: "en", local: "Wilhelminapark, the canals: students and young families.", dayRate: "€22–35", walkRate: "€12–20" },
  { slug: "the-hague", name: "The Hague", region: "Netherlands", lang: "en", local: "Scheveningen beach, Haagse Bos: diplomats and expats who travel constantly.", dayRate: "€25–40", walkRate: "€15–22" },
  { slug: "copenhagen", name: "Copenhagen", region: "Denmark", lang: "en", local: "Frederiksberg, Amager beach: design-minded owners with high expectations.", dayRate: "350–550 kr", walkRate: "180–280 kr" },
  { slug: "stockholm", name: "Stockholm", region: "Sweden", lang: "en", local: "Djurgården, Södermalm: long summer holidays and winter walks in demand.", dayRate: "350–550 kr", walkRate: "180–280 kr" },
  { slug: "gothenburg", name: "Gothenburg", region: "Sweden", lang: "en", local: "Slottsskogen, the archipelago: outdoor owners and holiday sitting.", dayRate: "300–500 kr", walkRate: "150–250 kr" },
  { slug: "oslo", name: "Oslo", region: "Norway", lang: "en", local: "Frognerparken, the Marka forests: hiking dogs and owners away at the cabin.", dayRate: "400–650 kr", walkRate: "200–320 kr" },
  { slug: "helsinki", name: "Helsinki", region: "Finland", lang: "en", local: "Central Park, Suomenlinna ferries: dogs in every neighbourhood, few sitters.", dayRate: "€25–40", walkRate: "€15–22" },
  { slug: "athens", name: "Athens", region: "Greece", lang: "en", local: "Kolonaki, Glyfada, Filopappou hill: early walks in summer, sitting during island trips.", dayRate: "€18–30", walkRate: "€10–16" },
  { slug: "prague", name: "Prague", region: "Czech Republic", lang: "en", local: "Letná, Vinohrady, Stromovka: one of Europe's most dog-friendly cities.", dayRate: "600–900 Kč", walkRate: "300–450 Kč" },
  { slug: "budapest", name: "Budapest", region: "Hungary", lang: "en", local: "Margaret Island, City Park: expats and locals who travel for work.", dayRate: "6,000–9,000 Ft", walkRate: "3,000–4,500 Ft" },
  { slug: "bucharest", name: "Bucharest", region: "Romania", lang: "en", local: "Herăstrău, Cișmigiu: a growing pet culture and almost no organised sitters.", dayRate: "80–130 lei", walkRate: "40–65 lei" },
  { slug: "zagreb", name: "Zagreb", region: "Croatia", lang: "en", local: "Maksimir park, Jarun lake: families with dogs, summer trips to the coast.", dayRate: "€18–30", walkRate: "€10–16" },
  { slug: "lisbon-en", name: "Lisbon", region: "Portugal (English)", lang: "en", local: "Expats and digital nomads: sitters who speak English are in demand.", dayRate: "€15–25", walkRate: "€8–14" },
  { slug: "barcelona-en", name: "Barcelona", region: "Spain (English)", lang: "en", local: "International residents around Gràcia and Poblenou looking for English-speaking sitters.", dayRate: "€18–28", walkRate: "€10–16" },
  { slug: "berlin-en", name: "Berlin", region: "Germany (English)", lang: "en", local: "The international crowd of Neukölln and Kreuzberg: English-speaking sitters wanted.", dayRate: "€20–30", walkRate: "€12–18" },
  { slug: "paris-en", name: "Paris", region: "France (English)", lang: "en", local: "Expats and English-speaking families across Paris looking for a trusted sitter.", dayRate: "€20–30", walkRate: "€12–20" },
  { slug: "valletta", name: "Valletta", region: "Malta", lang: "en", local: "Sliema, St Julian's: expats, sun and small dogs.", dayRate: "€18–28", walkRate: "€10–15" },
  { slug: "tallinn", name: "Tallinn", region: "Estonia", lang: "en", local: "Kadriorg, Pirita beach: tech workers with long days.", dayRate: "€20–30", walkRate: "€10–16" },
  { slug: "riga", name: "Riga", region: "Latvia", lang: "en", local: "Mežaparks, the seaside at Jūrmala: summer sitting in demand.", dayRate: "€18–28", walkRate: "€10–15" },
  { slug: "vilnius", name: "Vilnius", region: "Lithuania", lang: "en", local: "Vingis Park, Užupis: young owners, few sitters.", dayRate: "€18–28", walkRate: "€10–15" },
  { slug: "bratislava", name: "Bratislava", region: "Slovakia", lang: "en", local: "Sad Janka Kráľa, the Carpathian hills: hiking dogs and city walks.", dayRate: "€18–28", walkRate: "€10–15" },
  { slug: "ljubljana", name: "Ljubljana", region: "Slovenia", lang: "en", local: "Tivoli park, Rožnik hill: a green capital where every dog gets walked.", dayRate: "€18–28", walkRate: "€10–15" },
  { slug: "sofia", name: "Sofia", region: "Bulgaria", lang: "en", local: "Borisova gradina, Vitosha mountain: growing demand, no established sitters.", dayRate: "40–70 лв", walkRate: "20–35 лв" },
  { slug: "washington-dc", name: "Washington, DC", region: "Washington, DC, USA", lang: "en", local: "Rock Creek Park, Capitol Hill, Navy Yard: government and consulting hours mean midday walks every weekday.", dayRate: "$40–65", walkRate: "$20–35" },
  { slug: "las-vegas", name: "Las Vegas", region: "Las Vegas, USA", lang: "en", local: "Summerlin, Henderson: shift workers and travelers, early-morning walks in summer.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "orlando", name: "Orlando", region: "Orlando, USA", lang: "en", local: "Winter Park, Lake Nona: theme-park shifts and tourism jobs need flexible sitters.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "tampa", name: "Tampa", region: "Tampa, USA", lang: "en", local: "Hyde Park, Bayshore: waterfront walks and snowbird owners.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "nashville", name: "Nashville", region: "Nashville, USA", lang: "en", local: "East Nashville, 12 South, Shelby Park: a fast-growing city where supply lags demand.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "charlotte", name: "Charlotte", region: "Charlotte, USA", lang: "en", local: "NoDa, South End, Freedom Park: banking hours and lots of new residents.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "portland", name: "Portland", region: "Portland, USA", lang: "en", local: "Forest Park, Alberta, Sellwood: possibly the most dog-friendly city in the US.", dayRate: "$35–60", walkRate: "$18–30" },
  { slug: "minneapolis", name: "Minneapolis", region: "Minneapolis, USA", lang: "en", local: "Lake Harriet, Uptown, Northeast: lake walks in summer, sitting through the winter.", dayRate: "$30–55", walkRate: "$15–25" },
  { slug: "san-antonio", name: "San Antonio", region: "San Antonio, USA", lang: "en", local: "Alamo Heights, the River Walk: military families deploying and traveling.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "san-jose", name: "San Jose", region: "San Jose, USA", lang: "en", local: "Willow Glen, Almaden: tech commuters who need weekday walks.", dayRate: "$40–65", walkRate: "$20–30" },
  { slug: "sacramento", name: "Sacramento", region: "Sacramento, USA", lang: "en", local: "Midtown, Land Park, the American River trail: outdoor owners, few sitters.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "detroit", name: "Detroit", region: "Detroit, USA", lang: "en", local: "Corktown, Belle Isle: a rebuilding city with growing pet ownership.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "columbus", name: "Columbus", region: "Columbus, USA", lang: "en", local: "Short North, Clintonville: students and young families.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "indianapolis", name: "Indianapolis", region: "Indianapolis, USA", lang: "en", local: "Broad Ripple, Fountain Square: affordable city, lots of dogs, few sitters.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "kansas-city", name: "Kansas City", region: "Kansas City, USA", lang: "en", local: "Brookside, Westport: friendly neighborhoods where walkers keep clients for years.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "salt-lake-city", name: "Salt Lake City", region: "Salt Lake City, USA", lang: "en", local: "Sugar House, the Avenues, the canyons: hiking dogs and weekend trips.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "raleigh", name: "Raleigh", region: "Raleigh, USA", lang: "en", local: "Research Triangle, Five Points: tech and university workers with long days.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "pittsburgh", name: "Pittsburgh", region: "Pittsburgh, USA", lang: "en", local: "Lawrenceville, Squirrel Hill, Frick Park: hilly walks and loyal clients.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "baltimore", name: "Baltimore", region: "Baltimore, USA", lang: "en", local: "Fells Point, Federal Hill, Patterson Park: row houses and daily walks.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "st-louis", name: "St. Louis", region: "St. Louis, USA", lang: "en", local: "Forest Park, Tower Grove: HoPetSit already has a sitter here — early clients welcome.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "cleveland", name: "Cleveland", region: "Cleveland, USA", lang: "en", local: "Tremont, Lakewood, the Metroparks: affordable and dog-friendly.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "cincinnati", name: "Cincinnati", region: "Cincinnati, USA", lang: "en", local: "Over-the-Rhine, Hyde Park: families and young professionals.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "milwaukee", name: "Milwaukee", region: "Milwaukee, USA", lang: "en", local: "Bay View, the lakefront: lake walks and holiday sitting.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "new-orleans", name: "New Orleans", region: "New Orleans, USA", lang: "en", local: "Uptown, Bywater, Audubon Park: hospitality shifts and festival weekends.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "honolulu", name: "Honolulu", region: "Honolulu, USA", lang: "en", local: "Kaimuki, Kailua, Ala Moana beach park: HoPetSit has a sitter here already; island owners travel often.", dayRate: "$35–60", walkRate: "$18–30" },
  { slug: "naples-fl", name: "Naples, FL", region: "Naples, FL, USA", lang: "en", local: "Old Naples, Pelican Bay: snowbirds, small dogs and a HoPetSit sitter already on the map.", dayRate: "$35–60", walkRate: "$18–30" },
  { slug: "decatur-ga", name: "Decatur, GA", region: "Decatur, GA, USA", lang: "en", local: "Oakhurst, Glenlake Park: Atlanta's dog-friendly suburb with a HoPetSit sitter already here.", dayRate: "$30–50", walkRate: "$15–25" },
  { slug: "brunswick-ga", name: "Brunswick, GA", region: "Brunswick, GA, USA", lang: "en", local: "Coastal Georgia, the Golden Isles: beach walks and vacation sitting.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "oklahoma-city", name: "Oklahoma City", region: "Oklahoma City, USA", lang: "en", local: "Midtown, Lake Hefner: big yards and travelers.", dayRate: "$25–45", walkRate: "$12–22" },
  { slug: "tucson", name: "Tucson", region: "Tucson, USA", lang: "en", local: "Catalina foothills, Sabino Canyon: early desert walks and snowbird sitting.", dayRate: "$25–45", walkRate: "$12–22" },
];

export const RECRUIT_PATH_PREFIX: Record<RecruitLang, string> = {
  fr: "/devenir-petsitter",
  en: "/become-a-pet-sitter",
  pl: "/zostan-opiekunem",
  ko: "/pet-sitter-korea",
  es: "/ser-cuidador-de-mascotas",
  de: "/tiersitter-werden",
  it: "/diventare-pet-sitter",
  pt: "/ser-pet-sitter",
  ja: "/pet-sitter-japan",
};

export function recruitCitiesFor(lang: RecruitLang): RecruitCity[] {
  return RECRUIT_CITIES.filter((c) => c.lang === lang);
}

export function recruitCity(lang: RecruitLang, slug: string): RecruitCity | undefined {
  return RECRUIT_CITIES.find((c) => c.lang === lang && c.slug === slug);
}

export function recruitPaths(): string[] {
  return RECRUIT_CITIES.map((c) => `${RECRUIT_PATH_PREFIX[c.lang]}/${c.slug}`);
}

// v560 — pages côté PROPRIÉTAIRE « trouver un pet sitter à <ville> » (même
// donnée, deuxième intention de recherche). Composant OwnerCityPage.
export const OWNER_PATH_PREFIX: Record<RecruitLang, string> = {
  fr: "/garde-animaux",
  en: "/pet-sitting",
  pl: "/opieka-nad-zwierzetami",
  ko: "/pet-sitting-korea",
  es: "/cuidado-de-mascotas",
  de: "/tierbetreuung",
  it: "/custodia-animali",
  pt: "/cuidado-de-animais",
  ja: "/pet-sitting-japan",
};

export function ownerPaths(): string[] {
  return RECRUIT_CITIES.map((c) => `${OWNER_PATH_PREFIX[c.lang]}/${c.slug}`);
}
