/// Sprint 8 step 3 — Terms of Service in 6 languages.
///
/// AI-DRAFTED FIRST PASS — MUST BE REVIEWED BY A QUALIFIED LAWYER BEFORE
/// PRODUCTION USE. This text was generated by an AI assistant (Claude) to meet
/// Play Store / App Store requirements and cover the essential legal points
/// (publisher identification, RGPD, limitation of liability, etc.). It is NOT
/// a substitute for professional legal advice.
library;

const String termsVersion = '2.0'; // v23.1 — Airwallex, 72h rule, escrow 24h post-completion

const String _aiDisclaimerEn =
    '⚠️ AI-DRAFTED: This text was prepared by an AI assistant as a first pass '
    'to satisfy Play Store / App Store requirements. It covers the essential '
    "points but MUST be reviewed by a lawyer specialised in digital law before "
    'production use with real users.\n\n';

const String _aiDisclaimerFr =
    '⚠️ RÉDIGÉ PAR IA : ce texte a été préparé par une IA comme premier jet '
    'conforme aux exigences Play Store / App Store. Il couvre les points '
    'essentiels mais DOIT être relu par un avocat spécialisé en droit du '
    'numérique avant mise en production avec des utilisateurs réels.\n\n';

const String _aiDisclaimerEs =
    '⚠️ REDACTADO POR IA: este texto fue preparado por una IA como primer '
    'borrador conforme a los requisitos de Play Store / App Store. Cubre los '
    'puntos esenciales pero DEBE ser revisado por un abogado especializado en '
    'derecho digital antes de su uso en producción con usuarios reales.\n\n';

const String _aiDisclaimerDe =
    '⚠️ VON KI VERFASST: Dieser Text wurde von einer KI als erster Entwurf '
    'erstellt, um die Anforderungen von Play Store / App Store zu erfüllen. Er '
    'deckt die wesentlichen Punkte ab, MUSS jedoch vor dem Einsatz mit echten '
    'Nutzern von einem auf Digitalrecht spezialisierten Anwalt geprüft werden.\n\n';

const String _aiDisclaimerIt =
    '⚠️ REDATTO DA IA: questo testo è stato preparato da un\'IA come prima '
    'bozza conforme ai requisiti Play Store / App Store. Copre i punti '
    'essenziali ma DEVE essere rivisto da un avvocato specializzato in diritto '
    'digitale prima dell\'uso in produzione con utenti reali.\n\n';

const String _aiDisclaimerPt =
    '⚠️ REDIGIDO POR IA: este texto foi preparado por uma IA como primeiro '
    'esboço conforme os requisitos Play Store / App Store. Cobre os pontos '
    'essenciais mas DEVE ser revisto por um advogado especializado em direito '
    'digital antes da utilização em produção com utilizadores reais.\n\n';

const String _termsEn = r"""
# HopeTSIT — Terms of Service

Version 1.0 — Effective date: upon first publication to app stores.

## 1. Preamble and definitions

These Terms of Service ("Terms") govern access to and use of the HopeTSIT mobile application and platform (the "Service"). The Service is a technical intermediary connecting pet owners ("Petowners") and pet sitters ("Petsitters"), collectively "Users".

"Platform" means the HoPetSit app, its backend, the admin dashboard and all related services. "Booking" means a service agreed between a Petowner and a Petsitter. "Payment" means the sum paid by the Petowner for a Booking, processed by **Airwallex** (PCI-DSS Level 1 certified).

## 2. Acceptance of the Terms

By creating an account and using the Service, each User expressly accepts the current version of these Terms. The acceptance date and version are logged on the server. Continued use after a version change implies acceptance of the new Terms (see section 22).

## 3. Publisher identification

The Service is operated by **CARDELLI HERMANOS LIMITED** (company number 2671528), registered office at Flat/RM A 12/F ZJ 300, 300 Lockhart Road, Wan Chai, Hong Kong. Customer service contact: **hopetsit@gmail.com**.

## 4. Purpose of the Service — exclusion of liability

HopeTSIT is **exclusively a technical intermediary of introduction** between Petowners and Petsitters. CARDELLI HERMANOS LIMITED is **NOT** a party to the service contract concluded between a Petowner and a Petsitter. CARDELLI HERMANOS LIMITED is **NOT** responsible, under any circumstance, for damage, accidents, losses, illness or death of animals occurring during a service, nor for property damage or bodily injury suffered or caused by an animal, a Petowner or a Petsitter. Users acknowledge and accept that the service is performed under the exclusive responsibility of the parties to the Booking.

## 5. Registration and accounts

Registration requires a valid email address, a secure password and acceptance of the present Terms. Each User guarantees the accuracy of the information provided and undertakes to keep it up to date. Accounts are personal and non-transferable. Unauthorized use must be reported immediately to hopetsit@gmail.com.

## 6. Obligations of the Petowner

Petowners undertake to:

- provide exact information on their animal's health, behaviour and vaccinations;
- keep vaccinations up to date and provide the contact details of a reachable veterinarian;
- subscribe, at their discretion, to a private civil-liability insurance covering their animal;
- carry out a photo/video inventory at handover and return of the animal (strongly recommended);
- pay the agreed Booking amount through the Platform;
- treat Petsitters with respect and comply with the cancellation rules (section 11).

## 7. Obligations of the Petsitter

Petsitters undertake to:

- provide truthful information on their experience, availability and location;
- submit an identity document for verification before receiving their first payout;
- take all reasonable care to ensure the animal's well-being;
- inform the Petowner of any incident without delay;
- subscribe, at their discretion, to a civil-liability insurance covering the service;
- comply with the service description and the agreed schedule.

## 8. Insurance

Users are exclusively responsible for subscribing any insurance (civil liability, personal liability) they consider necessary. CARDELLI HERMANOS LIMITED strongly recommends each User to hold a private civil-liability insurance policy. CARDELLI HERMANOS LIMITED does NOT provide insurance coverage and disclaims any liability in this respect.

## 9. Booking and mutual acceptance

A Booking becomes firm and binding only after (i) acceptance by both parties and (ii) confirmation of Payment. Before Payment, either party may withdraw at no cost. After Payment, the cancellation rules of section 11 apply.

## 10. Payment

Payments are processed by **Airwallex** (Airwallex (UK) Limited / Airwallex (Hong Kong) Limited), a PCI-DSS Level 1 certified payment provider. HoPetSit never accesses, transmits or stores cardholder data. The platform commission is **twenty percent (20%)** of the Booking gross amount. Funds are held in escrow by Airwallex until **24 hours after the service ends**, at which point **80%** is released to the Petsitter's registered IBAN and **20%** is retained by HoPetSit as platform fee. Users accept that Airwallex's own terms apply to payment operations.

## 11. Cancellation and refund

- Cancellation by the Petowner more than **72 hours** before the service: **100% automatic refund** (self-cancel from the app).
- Cancellation **72 hours or less** before the service: self-cancellation is no longer available; the Petowner must agree on a **mutual cancellation** with the Petsitter, or open a formal dispute via hopetsit@gmail.com — refunds within this window are reviewed case-by-case.
- Cancellation by the Petsitter (regardless of delay): **100% refund** of the Petowner.
- No-show by the Petsitter: **100% refund** + provider penalty.
- After service has started: no refund, except via successful dispute resolution.

Refunds are processed through Airwallex back to the original payment card within 5 to 10 business days. See https://hopetsit.com/refund for the full Refund Policy.

## 12. Chat and private data

The in-app chat is unlocked **only after Payment confirmation** for the relevant Booking. Sharing of email addresses within the chat is **prohibited**; sharing a phone number is permitted after Payment. HopeTSIT reserves the right to automatically moderate chat messages to remove personal contact details not compliant with these rules.

## 13. Loyalty and referral program

Petowners completing 10 Bookings obtain the "Premium" status. Every third completed Booking grants a -10% discount credit, usable on the next Booking. The referral program grants a €5 credit to the referrer upon the referred user's first completed Booking. Credits are non-transferable, non-refundable in cash, non-cumulable with other promotional offers, and expire 12 months after issuance.

## 14. Intellectual property

All content published by HopeTSIT (brand, logo, texts, graphics, code) is the exclusive property of CARDELLI HERMANOS LIMITED. Users retain rights on the content they publish (photos, texts) but grant HopeTSIT a worldwide, royalty-free, non-exclusive licence to use this content for the operation and promotion of the Service.

## 15. Personal data (GDPR)

HoPetSit acts as a data controller for the personal data of its Users. Data is processed on the legal basis of contract execution and, where applicable, consent. Storage duration: account lifetime + 3 years for billing records. Sub-processors: Airwallex (payments — PCI-DSS Level 1 certified), Firebase (auth, push, crashlytics), Cloudinary (media), MongoDB Atlas (database), Google Maps (geolocation). Users have the rights of access, rectification, erasure, portability, and objection, exercisable at **hopetsit@gmail.com**. A detailed Privacy Policy is available inside the app.

## 16. Cookies and tracking

The mobile app uses local storage and analytics events strictly necessary for operation (session management, crash reports). No advertising trackers are used without explicit opt-in.

## 17. Moderation and sanctions

HopeTSIT reserves the right to moderate any User-published content, hide inappropriate reviews, suspend or ban accounts for serious or repeated breaches of these Terms. Three reports of a review trigger an internal alert. Banning is definitive and prevents any new registration.

## 18. Termination

A User may delete their account at any time from the in-app settings. Pending Bookings must first be resolved. Data is deleted within 30 days of deletion, except for legal retention obligations.

## 19. Limitation of liability

Within the maximum limits of applicable law, CARDELLI HERMANOS LIMITED's liability is excluded for any indirect damage, loss of profit, loss of data, or commercial damage. In any event, the maximum aggregate liability of CARDELLI HERMANOS LIMITED is capped at the amount of the User's most recent transaction via the Platform. Force-majeure events suspend all obligations.

## 20. Applicable law

These Terms are governed by the **laws of Hong Kong SAR**, except to the extent that mandatory consumer protection rules of the User's residence country apply. Any dispute that cannot be resolved amicably is submitted to **arbitration before the Hong Kong International Arbitration Centre (HKIAC)**, or, at the User's option if a consumer under EU law, to the competent courts of the User's residence country.

## 21. Customer service

For any question or complaint, please contact **hopetsit@gmail.com**. An initial response is provided within 5 business days.

## 22. Modification of the Terms

HopeTSIT may modify these Terms. A **30-day notice** is sent to active Users before the new version enters into force. Continued use beyond this period implies acceptance of the new version. A User refusing the new version may terminate their account as provided in section 18.
""";

const String _termsFr = r"""
# HopeTSIT — Conditions Générales d'Utilisation

Version 1.0 — Date d'effet : dès la première publication sur les stores.

## 1. Préambule et définitions

Les présentes Conditions Générales d'Utilisation (« CGU ») régissent l'accès et l'utilisation de l'application mobile et de la plateforme HopeTSIT (le « Service »). Le Service est un intermédiaire technique mettant en relation des propriétaires d'animaux (« Petowners ») et des gardiens d'animaux (« Petsitters »), ensemble les « Utilisateurs ».

« Plateforme » désigne l'application HoPetSit, son backend, le tableau de bord admin et tous les services associés. « Réservation » désigne une prestation convenue entre un Petowner et un Petsitter. « Paiement » désigne la somme payée par le Petowner pour une Réservation, traitée par **Airwallex** (certifié PCI-DSS Niveau 1).

## 2. Acceptation des CGU

Par la création d'un compte et l'utilisation du Service, chaque Utilisateur accepte expressément la version en vigueur des présentes CGU. La date et la version d'acceptation sont enregistrées côté serveur. L'utilisation continue après un changement de version vaut acceptation des nouvelles CGU (cf. article 22).

## 3. Identification de l'éditeur

Le Service est édité par **CARDELLI HERMANOS LIMITED** (numéro de société 2671528), siège social Flat/RM A 12/F ZJ 300, 300 Lockhart Road, Wan Chai, Hong Kong. Contact service client : **hopetsit@gmail.com**.

## 4. Objet du Service — exclusion de responsabilité

HopeTSIT est **exclusivement un intermédiaire technique de mise en relation** entre Petowners et Petsitters. CARDELLI HERMANOS LIMITED n'est **PAS** partie au contrat de prestation conclu entre un Petowner et un Petsitter. CARDELLI HERMANOS LIMITED n'est **PAS** responsable, en aucune circonstance, des dommages, accidents, pertes, maladies ou décès d'animaux survenus pendant une prestation, ni des dommages matériels ou corporels subis ou causés par un animal, un Petowner ou un Petsitter. Les Utilisateurs reconnaissent et acceptent que la prestation est effectuée sous la responsabilité exclusive des parties à la Réservation.

## 5. Inscription et comptes

L'inscription nécessite une adresse email valide, un mot de passe sécurisé et l'acceptation des présentes CGU. Chaque Utilisateur garantit l'exactitude des informations fournies et s'engage à les tenir à jour. Les comptes sont personnels et incessibles. Toute utilisation non autorisée doit être signalée sans délai à hopetsit@gmail.com.

## 6. Obligations du Petowner

Le Petowner s'engage à :

- fournir des informations exactes sur la santé, le comportement et les vaccinations de son animal ;
- maintenir les vaccinations à jour et communiquer les coordonnées d'un vétérinaire joignable ;
- souscrire, à sa discrétion, une assurance responsabilité civile vie privée couvrant son animal ;
- réaliser un état des lieux photo/vidéo à la remise et à la restitution de l'animal (vivement recommandé) ;
- régler le montant de la Réservation via la Plateforme ;
- traiter les Petsitters avec respect et se conformer aux règles d'annulation (article 11).

## 7. Obligations du Petsitter

Le Petsitter s'engage à :

- fournir des informations sincères sur son expérience, sa disponibilité et sa localisation ;
- soumettre une pièce d'identité pour vérification avant son premier versement ;
- prendre toutes les précautions raisonnables pour garantir le bien-être de l'animal ;
- informer le Petowner sans délai de tout incident ;
- souscrire, à sa discrétion, une assurance responsabilité civile couvrant la prestation ;
- respecter la description de la prestation et le planning convenu.

## 8. Assurances

La souscription de toute assurance (responsabilité civile, assurance personnelle) jugée nécessaire relève de la responsabilité exclusive des Utilisateurs. CARDELLI HERMANOS LIMITED recommande vivement à chaque Utilisateur de disposer d'une assurance responsabilité civile vie privée. CARDELLI HERMANOS LIMITED ne fournit AUCUNE couverture d'assurance et décline toute responsabilité à cet égard.

## 9. Réservation et acceptation mutuelle

Une Réservation devient ferme et définitive uniquement après (i) acceptation des deux parties et (ii) confirmation du Paiement. Avant le Paiement, chacune des parties peut se rétracter sans frais. Après le Paiement, les règles d'annulation de l'article 11 s'appliquent.

## 10. Paiement

Les paiements sont traités par **Airwallex** (Airwallex (UK) Limited / Airwallex (Hong Kong) Limited), prestataire de paiement certifié PCI-DSS Niveau 1. HoPetSit n'accède jamais aux données de carte bancaire. La commission plateforme est de **vingt pour cent (20 %)** du montant brut de la Réservation. Les fonds sont retenus en séquestre par Airwallex jusqu'à **24 heures après la fin du service**, puis **80 %** sont libérés vers l'IBAN enregistré du Petsitter et **20 %** sont conservés par HoPetSit en frais plateforme. Les Utilisateurs acceptent que les conditions d'Airwallex s'appliquent aux opérations de paiement.

## 11. Annulation et remboursement

- Annulation par le Petowner plus de **72 heures** avant la prestation : **remboursement automatique à 100 %** (auto-annulation depuis l'application).
- Annulation **72 heures ou moins** avant la prestation : l'auto-annulation n'est plus disponible ; le Petowner doit convenir d'une **annulation mutuelle** avec le Petsitter, ou ouvrir un litige formel via hopetsit@gmail.com — les remboursements dans cette fenêtre sont étudiés au cas par cas.
- Annulation par le Petsitter (quel que soit le délai) : **remboursement intégral à 100 %** du Petowner.
- No-show du Petsitter : **remboursement intégral** + pénalité prestataire.
- Après le début de la prestation : pas de remboursement, sauf via résolution de litige favorable.

Les remboursements sont effectués via Airwallex vers la carte de paiement d'origine sous 5 à 10 jours ouvrés. Voir https://hopetsit.com/remboursement pour la Politique de Remboursement complète.

## 12. Chat et données privées

Le chat dans l'application est débloqué **uniquement après confirmation du Paiement** pour la Réservation concernée. Le partage d'adresses email dans le chat est **interdit** ; le partage d'un numéro de téléphone est autorisé après Paiement. HopeTSIT se réserve le droit de modérer automatiquement les messages afin de supprimer les coordonnées personnelles non conformes.

## 13. Programme de fidélité et parrainage

Les Petowners ayant complété 10 Réservations obtiennent le statut « Premium ». Toutes les 3 Réservations complétées, un crédit de -10 % est offert, utilisable sur la Réservation suivante. Le programme de parrainage accorde un crédit de 5 € au parrain lors de la 1ère Réservation complétée par son filleul. Les crédits sont non cessibles, non remboursables en espèces, non cumulables avec d'autres offres promotionnelles et expirent 12 mois après leur émission.

## 14. Propriété intellectuelle

L'ensemble des contenus publiés par HopeTSIT (marque, logo, textes, graphismes, code) est la propriété exclusive de CARDELLI HERMANOS LIMITED. Les Utilisateurs conservent leurs droits sur les contenus qu'ils publient (photos, textes) mais concèdent à HopeTSIT une licence mondiale, à titre gratuit et non exclusif, pour l'exploitation et la promotion du Service.

## 15. Données personnelles (RGPD)

HoPetSit agit en qualité de responsable de traitement. Le traitement est fondé sur l'exécution du contrat et, le cas échéant, sur le consentement. Durée de conservation : durée de vie du compte + 3 ans pour les pièces de facturation. Sous-traitants : Airwallex (paiements — certifié PCI-DSS Niveau 1), Firebase (auth, push, crash), Cloudinary (médias), MongoDB Atlas (base de données), Google Maps (géolocalisation). Les Utilisateurs disposent des droits d'accès, de rectification, d'effacement, de portabilité et d'opposition, à exercer à **hopetsit@gmail.com**. Une Politique de confidentialité détaillée est disponible dans l'application.

## 16. Cookies et traceurs

L'application mobile utilise un stockage local et des événements d'analyse strictement nécessaires au fonctionnement (gestion de session, rapports de plantage). Aucun traceur publicitaire n'est utilisé sans consentement explicite.

## 17. Modération et sanctions

HopeTSIT se réserve le droit de modérer tout contenu publié par les Utilisateurs, de masquer un avis inapproprié, et de suspendre ou bannir un compte en cas de manquement grave ou répété. Trois signalements d'un avis déclenchent une alerte interne. Le bannissement est définitif et empêche toute nouvelle inscription.

## 18. Résiliation

Chaque Utilisateur peut supprimer son compte à tout moment depuis les paramètres de l'application. Les Réservations en cours doivent être soldées au préalable. Les données sont supprimées sous 30 jours, sauf obligation légale de conservation.

## 19. Responsabilité limitée

Dans les limites maximales autorisées par la loi applicable, la responsabilité de CARDELLI HERMANOS LIMITED est exclue pour tout dommage indirect, perte de profit, perte de données ou préjudice commercial. En tout état de cause, la responsabilité maximale agrégée de CARDELLI HERMANOS LIMITED est plafonnée au montant de la dernière transaction de l'Utilisateur via la Plateforme. Les événements de force majeure suspendent toutes les obligations.

## 20. Droit applicable

Les présentes CGU sont régies par la **loi de la Région administrative spéciale de Hong Kong**, sous réserve des règles impératives de protection des consommateurs du pays de résidence de l'Utilisateur. Tout litige non résolu à l'amiable est soumis à **arbitrage devant le Hong Kong International Arbitration Centre (HKIAC)** ou, au choix de l'Utilisateur consommateur UE, aux tribunaux compétents du pays de résidence de l'Utilisateur.

## 21. Service client

Pour toute question ou réclamation, contactez **hopetsit@gmail.com**. Une première réponse est apportée sous 5 jours ouvrés.

## 22. Modification des CGU

HopeTSIT peut modifier les présentes CGU. Un **préavis de 30 jours** est adressé aux Utilisateurs actifs avant l'entrée en vigueur de la nouvelle version. L'utilisation continue au-delà vaut acceptation. Un Utilisateur refusant la nouvelle version peut résilier son compte selon l'article 18.
""";

const String _termsEs = r"""
# HopeTSIT — Términos y Condiciones

Versión 1.0 — Fecha de entrada en vigor: desde la primera publicación en las tiendas.

## 1. Preámbulo y definiciones

Los presentes Términos y Condiciones regulan el acceso y uso de la aplicación móvil y la plataforma HopeTSIT (el "Servicio"). El Servicio es un intermediario técnico que pone en contacto a propietarios de animales ("Petowners") y cuidadores de animales ("Petsitters"), conjuntamente los "Usuarios".

## 2. Aceptación

Al crear una cuenta, cada Usuario acepta expresamente los presentes Términos. La fecha y la versión de aceptación se registran en el servidor. El uso continuado tras un cambio de versión supone la aceptación de los nuevos Términos (art. 22).

## 3. Identificación del editor

El Servicio es operado por **CARDELLI HERMANOS LIMITED** (n.º 2671528), con domicilio social en Flat/RM A 12/F ZJ 300, 300 Lockhart Road, Wan Chai, Hong Kong. Contacto: **hopetsit@gmail.com**.

## 4. Objeto — exclusión de responsabilidad

HopeTSIT es **exclusivamente un intermediario técnico de puesta en contacto**. CARDELLI HERMANOS LIMITED **NO** es parte del contrato celebrado entre Petowners y Petsitters. CARDELLI HERMANOS LIMITED **NO** se hace responsable, bajo ninguna circunstancia, de daños, accidentes, pérdidas, enfermedades o muerte de animales durante la prestación, ni de daños materiales o corporales causados por un animal, un Petowner o un Petsitter.

## 5. Registro

El registro requiere un correo electrónico válido, una contraseña segura y la aceptación de los presentes Términos. Las cuentas son personales e intransferibles.

## 6. Obligaciones del Petowner

El Petowner se compromete a:

- proporcionar información exacta sobre la salud y vacunación del animal;
- mantener las vacunas al día y facilitar un veterinario localizable;
- suscribir, a su criterio, un seguro de responsabilidad civil privada;
- realizar una verificación fotográfica/vídeo al entregar y recuperar el animal (muy recomendado);
- pagar el importe pactado a través de la Plataforma;
- tratar al Petsitter con respeto y respetar las reglas de cancelación (art. 11).

## 7. Obligaciones del Petsitter

El Petsitter se compromete a:

- proporcionar información veraz sobre su experiencia, disponibilidad y ubicación;
- presentar un documento de identidad para verificación antes del primer pago;
- adoptar todas las precauciones razonables para garantizar el bienestar del animal;
- informar al Petowner sin demora de cualquier incidente;
- suscribir, a su criterio, un seguro de responsabilidad civil cubriendo el servicio;
- respetar la descripción del servicio y el calendario acordado.

## 8. Seguros

La suscripción de cualquier seguro corresponde exclusivamente a los Usuarios. CARDELLI HERMANOS LIMITED recomienda encarecidamente un seguro de responsabilidad civil privada. CARDELLI HERMANOS LIMITED no ofrece ninguna cobertura y declina cualquier responsabilidad al respecto.

## 9. Reserva y aceptación mutua

Una reserva es firme solo tras (i) la aceptación de ambas partes y (ii) la confirmación del pago. Antes del pago, cualquiera de las partes puede retractarse sin coste. Después del pago se aplican las reglas de cancelación (art. 11).

## 10. Pago

Los pagos son procesados por **Airwallex**, un proveedor de pagos certificado PCI-DSS Nivel 1. HoPetSit nunca accede a los datos de la tarjeta. La comisión de la plataforma es del **veinte por ciento (20 %)** del importe bruto. Los fondos se mantienen en custodia hasta **24 horas después del fin del servicio**, momento en que el **80 %** se libera al IBAN del Petsitter y el **20 %** se retiene como comisión de plataforma.

## 11. Cancelación y reembolso

- Más de **72 horas** antes del servicio: **reembolso automático del 100 %** (auto-cancelación desde la app).
- **72 horas o menos** antes del servicio: la auto-cancelación ya no está disponible; se requiere **cancelación mutua** o un litigio formal vía hopetsit@gmail.com — los reembolsos se evalúan caso por caso.
- Cancelación por parte del Petsitter: **reembolso íntegro del 100 %** del Petowner.
- No-show del Petsitter: **reembolso íntegro** + sanción al prestador.
- Tras el inicio del servicio: sin reembolso, salvo resolución favorable de un litigio.

Los reembolsos se procesan vía Airwallex hacia la tarjeta original en 5-10 días hábiles. Ver https://hopetsit.com/refund para la Política de Reembolso completa.

## 12. Chat

El chat se desbloquea **solo tras la confirmación del pago**. Compartir correos electrónicos está **prohibido**; compartir un teléfono está permitido después del pago. HopeTSIT se reserva el derecho a moderar los mensajes.

## 13. Fidelidad y referidos

Los Petowners que completen 10 reservas obtienen el estado "Premium". Cada 3 reservas completadas se concede un crédito del -10 %. El programa de referidos concede 5 € al referente tras la 1.ª reserva completada del referido. Los créditos son intransferibles, no reembolsables en efectivo, no acumulables con otras promociones, y caducan a los 12 meses.

## 14. Propiedad intelectual

Todos los contenidos publicados por HopeTSIT son propiedad exclusiva de CARDELLI HERMANOS LIMITED. Los Usuarios conservan los derechos sobre sus contenidos pero otorgan a HopeTSIT una licencia mundial, gratuita y no exclusiva para la operación y promoción del Servicio.

## 15. Datos personales (RGPD)

HoPetSit actúa como responsable del tratamiento. Base legal: ejecución del contrato y, en su caso, consentimiento. Plazo de conservación: vida útil de la cuenta + 3 años para facturación. Encargados: Airwallex (pagos — PCI-DSS Nivel 1), Firebase, Cloudinary, MongoDB Atlas, Google Maps. Derechos de acceso, rectificación, supresión, portabilidad y oposición ejercibles en **hopetsit@gmail.com**.

## 16. Cookies

La app móvil usa almacenamiento local y eventos estrictamente necesarios. Sin trackers publicitarios sin consentimiento explícito.

## 17. Moderación y sanciones

HopeTSIT puede moderar cualquier contenido, ocultar valoraciones inapropiadas, suspender o expulsar cuentas por incumplimientos graves o repetidos. Tres denuncias de una valoración activan una alerta interna.

## 18. Terminación

El Usuario puede eliminar su cuenta en cualquier momento desde los ajustes. Las reservas pendientes deben resolverse antes. Los datos se eliminan en 30 días, salvo obligación legal de conservación.

## 19. Responsabilidad limitada

En los límites máximos permitidos por la ley, se excluye la responsabilidad de CARDELLI HERMANOS LIMITED por daños indirectos, lucro cesante, pérdida de datos o perjuicio comercial. La responsabilidad máxima agregada se limita al importe de la última transacción del Usuario. La fuerza mayor suspende todas las obligaciones.

## 20. Ley aplicable

Los presentes Términos se rigen por la **ley de Hong Kong SAR**, sin perjuicio de las normas imperativas de protección del consumidor del país de residencia del Usuario. Los litigios se someten al **HKIAC**, o a discreción del Usuario consumidor UE, a los tribunales de su país de residencia.

## 21. Atención al cliente

**hopetsit@gmail.com**. Primera respuesta en 5 días hábiles.

## 22. Modificación

Preaviso de **30 días** antes de la entrada en vigor de una nueva versión. El uso continuado implica aceptación. La denegación permite resolver la cuenta (art. 18).
""";

const String _termsDe = r"""
# HopeTSIT — Nutzungsbedingungen

Version 1.0 — Inkrafttreten: ab der ersten Veröffentlichung in den App-Stores.

## 1. Präambel und Definitionen

Diese Nutzungsbedingungen regeln den Zugang zur und die Nutzung der mobilen Anwendung und der Plattform HopeTSIT (der "Dienst"). Der Dienst ist ein technischer Vermittler zwischen Tierhaltern ("Petowners") und Tierbetreuern ("Petsitters"), gemeinsam die "Nutzer".

## 2. Annahme

Mit der Kontoerstellung nimmt jeder Nutzer die aktuelle Fassung dieser Bedingungen ausdrücklich an. Datum und Version der Annahme werden serverseitig protokolliert. Die fortgesetzte Nutzung nach einer Versionsänderung gilt als Annahme der neuen Bedingungen (Art. 22).

## 3. Anbieterkennung

Der Dienst wird betrieben von **CARDELLI HERMANOS LIMITED** (Gesellschaftsnummer 2671528), Sitz Flat/RM A 12/F ZJ 300, 300 Lockhart Road, Wan Chai, Hongkong. Kundenservice: **hopetsit@gmail.com**.

## 4. Zweck — Haftungsausschluss

HopeTSIT ist **ausschließlich ein technischer Vermittler**. CARDELLI HERMANOS LIMITED ist **KEINE** Vertragspartei des Betreuungsvertrags zwischen Petowners und Petsitters. CARDELLI HERMANOS LIMITED haftet unter keinen Umständen für Schäden, Unfälle, Verluste, Krankheiten oder Tod von Tieren während eines Dienstes, noch für Sach- oder Personenschäden.

## 5. Registrierung

Die Registrierung erfordert eine gültige E-Mail-Adresse, ein sicheres Passwort und die Annahme dieser Bedingungen. Konten sind persönlich und nicht übertragbar.

## 6. Pflichten des Petowners

Der Petowner verpflichtet sich insbesondere: genaue Angaben zu Gesundheit und Impfstatus des Tieres zu machen; einen erreichbaren Tierarzt anzugeben; nach eigenem Ermessen eine private Haftpflichtversicherung abzuschließen; bei Übergabe und Rückgabe eine Foto-/Video-Bestandsaufnahme zu erstellen (empfohlen); den vereinbarten Betrag über die Plattform zu zahlen; sich an die Stornoregeln (Art. 11) zu halten.

## 7. Pflichten des Petsitters

Der Petsitter verpflichtet sich insbesondere: wahrheitsgemäße Angaben zu Erfahrung, Verfügbarkeit und Ort zu machen; vor der ersten Auszahlung ein Ausweisdokument zur Verifizierung einzureichen; alle zumutbaren Vorkehrungen für das Wohl des Tieres zu treffen; den Petowner unverzüglich über Vorfälle zu informieren; die Dienstbeschreibung und den vereinbarten Zeitplan einzuhalten.

## 8. Versicherungen

Der Abschluss von Versicherungen liegt ausschließlich in der Verantwortung der Nutzer. CARDELLI HERMANOS LIMITED empfiehlt dringend eine private Haftpflichtversicherung. CARDELLI HERMANOS LIMITED bietet keinerlei Versicherungsdeckung.

## 9. Buchung und gegenseitige Annahme

Eine Buchung wird erst nach (i) Annahme durch beide Parteien und (ii) Zahlungsbestätigung verbindlich. Vor der Zahlung kann jede Partei kostenfrei zurücktreten. Nach der Zahlung gelten die Stornoregeln (Art. 11).

## 10. Zahlung

Zahlungen werden von **Airwallex** (PCI-DSS Level 1 zertifiziert) abgewickelt. HoPetSit greift niemals auf Kartendaten zu. Die Plattform-Provision beträgt **zwanzig Prozent (20 %)** des Bruttobuchungsbetrags. Die Gelder werden bis **24 Stunden nach Ende der Leistung** bei Airwallex treuhänderisch verwahrt; danach werden **80 %** an die hinterlegte IBAN des Petsitters ausgezahlt und **20 %** als Plattformgebühr einbehalten.

## 11. Stornierung und Erstattung

- Stornierung durch den Petowner mehr als **72 Stunden** vor der Leistung: **100 % automatische Rückerstattung** (Selbst-Stornierung in der App).
- **72 Stunden oder weniger** vor der Leistung: Selbst-Stornierung nicht mehr verfügbar; eine **gegenseitige Stornierung** mit dem Petsitter oder ein formelles Streitverfahren über hopetsit@gmail.com ist erforderlich — Rückerstattungen werden im Einzelfall geprüft.
- Stornierung durch den Petsitter: **100 % volle Rückerstattung** des Petowners.
- No-Show des Petsitters: **volle Rückerstattung** + Sanktion gegen den Anbieter.
- Nach Beginn der Leistung: keine Rückerstattung, außer durch erfolgreiche Streitbeilegung.

Rückerstattungen erfolgen über Airwallex auf die ursprüngliche Zahlungskarte in 5–10 Werktagen. Vollständige Rückerstattungsrichtlinie unter https://hopetsit.com/refund.

## 12. Chat

Der Chat wird **erst nach Zahlungsbestätigung** freigeschaltet. Das Teilen von E-Mail-Adressen ist **untersagt**; das Teilen einer Telefonnummer ist nach Zahlung erlaubt.

## 13. Treue- und Empfehlungsprogramm

Petowners erhalten den "Premium"-Status nach 10 abgeschlossenen Buchungen. Alle 3 abgeschlossenen Buchungen gibt es ein -10 %-Guthaben. Das Empfehlungsprogramm gewährt 5 € Guthaben bei der 1. abgeschlossenen Buchung des Geworbenen. Guthaben sind nicht übertragbar, nicht auszahlbar, nicht mit anderen Aktionen kombinierbar und verfallen nach 12 Monaten.

## 14. Geistiges Eigentum

Alle von HopeTSIT veröffentlichten Inhalte sind ausschließliches Eigentum von CARDELLI HERMANOS LIMITED. Nutzer behalten Rechte an eigenen Inhalten, gewähren HopeTSIT jedoch eine weltweite, unentgeltliche, nicht ausschließliche Lizenz.

## 15. Personenbezogene Daten (DSGVO)

HoPetSit ist Verantwortlicher. Rechtsgrundlage: Vertragserfüllung und ggf. Einwilligung. Aufbewahrung: Kontolaufzeit + 3 Jahre für Abrechnungsunterlagen. Auftragsverarbeiter: Airwallex (Zahlungen — PCI-DSS Level 1), Firebase, Cloudinary, MongoDB Atlas, Google Maps. Rechte auf Auskunft, Berichtigung, Löschung, Übertragbarkeit und Widerspruch: **hopetsit@gmail.com**.

## 16. Cookies

Die App nutzt lokalen Speicher und für den Betrieb erforderliche Analyseereignisse. Keine Werbetracker ohne ausdrückliche Einwilligung.

## 17. Moderation

HopeTSIT behält sich das Recht vor, Inhalte zu moderieren, Bewertungen auszublenden, Konten zu sperren oder zu verbannen. Drei Meldungen einer Bewertung lösen eine interne Warnung aus.

## 18. Kündigung

Nutzer können ihr Konto jederzeit aus den Einstellungen löschen. Laufende Buchungen müssen zuvor abgewickelt werden. Datenlöschung innerhalb von 30 Tagen, vorbehaltlich gesetzlicher Aufbewahrungspflichten.

## 19. Haftungsbeschränkung

Im gesetzlich zulässigen Rahmen ist die Haftung für mittelbare Schäden, entgangenen Gewinn, Datenverlust oder wirtschaftlichen Schaden ausgeschlossen. Die maximale Gesamthaftung ist auf den Betrag der letzten Nutzer-Transaktion begrenzt. Höhere Gewalt setzt alle Pflichten aus.

## 20. Anwendbares Recht

Diese Bedingungen unterliegen dem **Recht der Sonderverwaltungsregion Hongkong**, unbeschadet zwingender Verbraucherschutzvorschriften des Wohnsitzlandes des Nutzers. Streitigkeiten werden dem **HKIAC** unterbreitet oder — nach Wahl des EU-Verbrauchers — den zuständigen Gerichten seines Wohnsitzlandes.

## 21. Kundenservice

**hopetsit@gmail.com**. Erstantwort innerhalb von 5 Werktagen.

## 22. Änderung

**30 Tage** Vorankündigung vor Inkrafttreten einer neuen Version. Fortgesetzte Nutzung gilt als Annahme.
""";

const String _termsIt = r"""
# HopeTSIT — Termini e Condizioni

Versione 1.0 — Data di entrata in vigore: dalla prima pubblicazione sugli store.

## 1. Premessa e definizioni

I presenti Termini e Condizioni regolano l'accesso e l'uso dell'applicazione mobile e della piattaforma HopeTSIT (il "Servizio"). Il Servizio è un intermediario tecnico che mette in contatto proprietari di animali ("Petowners") e pet sitter ("Petsitters"), insieme gli "Utenti".

## 2. Accettazione

Con la creazione di un account, ogni Utente accetta espressamente la versione in vigore dei presenti Termini. Data e versione dell'accettazione sono registrate sul server. L'uso continuato dopo un cambio di versione implica l'accettazione dei nuovi Termini (art. 22).

## 3. Identificazione dell'editore

Il Servizio è gestito da **CARDELLI HERMANOS LIMITED** (n. 2671528), sede legale Flat/RM A 12/F ZJ 300, 300 Lockhart Road, Wan Chai, Hong Kong. Contatto: **hopetsit@gmail.com**.

## 4. Oggetto — esclusione di responsabilità

HopeTSIT è **esclusivamente un intermediario tecnico**. CARDELLI HERMANOS LIMITED **NON** è parte del contratto tra Petowners e Petsitters. CARDELLI HERMANOS LIMITED **NON** è responsabile, in alcuna circostanza, di danni, incidenti, perdite, malattie o decessi di animali durante la prestazione, né di danni materiali o personali.

## 5. Registrazione

La registrazione richiede un'email valida, una password sicura e l'accettazione dei Termini. Gli account sono personali e non cedibili.

## 6. Obblighi del Petowner

Il Petowner si impegna a: fornire informazioni esatte su salute e vaccinazioni dell'animale; mantenere le vaccinazioni aggiornate e comunicare un veterinario reperibile; sottoscrivere, a sua discrezione, un'assicurazione RC privata; effettuare un inventario foto/video alla consegna e restituzione (raccomandato); pagare l'importo pattuito tramite la Piattaforma; rispettare le regole di cancellazione (art. 11).

## 7. Obblighi del Petsitter

Il Petsitter si impegna a: fornire informazioni veritiere su esperienza, disponibilità e ubicazione; inviare un documento d'identità per la verifica prima del primo pagamento; adottare tutte le precauzioni ragionevoli per il benessere dell'animale; informare tempestivamente il Petowner di qualsiasi incidente; rispettare la descrizione del servizio e il calendario pattuito.

## 8. Assicurazioni

La sottoscrizione di qualsiasi assicurazione spetta esclusivamente agli Utenti. CARDELLI HERMANOS LIMITED raccomanda vivamente un'assicurazione RC privata. CARDELLI HERMANOS LIMITED non offre alcuna copertura.

## 9. Prenotazione e accettazione reciproca

Una prenotazione diventa definitiva solo dopo (i) l'accettazione di entrambe le parti e (ii) la conferma del pagamento. Prima del pagamento, ciascuna parte può ritirarsi senza costi. Dopo il pagamento si applicano le regole di cancellazione (art. 11).

## 10. Pagamento

I pagamenti sono gestiti da **Airwallex** (certificato PCI-DSS Livello 1). HoPetSit non accede mai ai dati delle carte. La commissione della piattaforma è del **venti per cento (20 %)** dell'importo lordo della Prenotazione. I fondi sono custoditi da Airwallex fino a **24 ore dopo la fine del servizio**, poi l'**80 %** viene rilasciato sull'IBAN del Petsitter e il **20 %** trattenuto come commissione di piattaforma.

## 11. Cancellazione e rimborso

- Più di **72 ore** prima del servizio: **rimborso automatico al 100 %** (auto-cancellazione dall'app).
- **72 ore o meno** prima del servizio: l'auto-cancellazione non è più disponibile; è richiesta una **cancellazione mutuale** o un litigio formale via hopetsit@gmail.com — rimborsi valutati caso per caso.
- Cancellazione da parte del Petsitter: **rimborso integrale al 100 %** del Petowner.
- No-show del Petsitter: **rimborso integrale** + sanzione al fornitore.
- Dopo l'inizio del servizio: nessun rimborso, salvo risoluzione favorevole di un litigio.

Rimborsi via Airwallex sulla carta originale in 5-10 giorni lavorativi. Politica di rimborso completa su https://hopetsit.com/refund.

## 12. Chat

La chat si sblocca **solo dopo la conferma del pagamento**. La condivisione di email è **vietata**; la condivisione di un numero di telefono è permessa dopo il pagamento.

## 13. Fedeltà e referral

I Petowners che completano 10 prenotazioni ottengono lo stato "Premium". Ogni 3 prenotazioni completate un credito del -10 %. Il programma referral concede 5 € al referrer alla 1ª prenotazione completata del referral. I crediti sono non cedibili, non rimborsabili in contanti, non cumulabili e scadono dopo 12 mesi.

## 14. Proprietà intellettuale

Tutti i contenuti pubblicati da HopeTSIT sono proprietà esclusiva di CARDELLI HERMANOS LIMITED. Gli Utenti mantengono i diritti sui propri contenuti ma concedono a HopeTSIT una licenza mondiale, gratuita e non esclusiva.

## 15. Dati personali (GDPR)

HoPetSit è titolare del trattamento. Base giuridica: esecuzione del contratto e, se del caso, consenso. Conservazione: durata dell'account + 3 anni per fatturazione. Responsabili: Airwallex (pagamenti — PCI-DSS Livello 1), Firebase, Cloudinary, MongoDB Atlas, Google Maps. Diritti di accesso, rettifica, cancellazione, portabilità e opposizione: **hopetsit@gmail.com**.

## 16. Cookie

L'app usa storage locale ed eventi strettamente necessari. Nessun tracker pubblicitario senza consenso esplicito.

## 17. Moderazione

HopeTSIT può moderare i contenuti, nascondere recensioni inappropriate, sospendere o bandire account. Tre segnalazioni attivano un'allerta interna.

## 18. Cessazione

L'Utente può eliminare il proprio account in qualsiasi momento dalle impostazioni. Le prenotazioni in corso devono essere prima risolte. Dati eliminati entro 30 giorni, salvo obblighi legali.

## 19. Responsabilità limitata

Nei limiti massimi consentiti dalla legge, è esclusa la responsabilità per danni indiretti, lucro cessante, perdita di dati o danno commerciale. La responsabilità massima è limitata all'importo dell'ultima transazione dell'Utente.

## 20. Legge applicabile

Si applica la **legge della SAR di Hong Kong**, salve le norme imperative di tutela del consumatore del paese di residenza. Controversie al **HKIAC** o, a scelta del consumatore UE, ai tribunali del paese di residenza.

## 21. Assistenza clienti

**hopetsit@gmail.com**. Prima risposta entro 5 giorni lavorativi.

## 22. Modifica

**30 giorni** di preavviso prima dell'entrata in vigore. L'uso continuato implica accettazione.
""";

const String _termsPt = r"""
# HopeTSIT — Termos e Condições

Versão 1.0 — Data de entrada em vigor: a partir da primeira publicação nas stores.

## 1. Preâmbulo e definições

Os presentes Termos e Condições regulam o acesso e a utilização da aplicação móvel e da plataforma HopeTSIT (o "Serviço"). O Serviço é um intermediário técnico que coloca em contacto proprietários de animais ("Petowners") e cuidadores de animais ("Petsitters"), em conjunto os "Utilizadores".

## 2. Aceitação

Ao criar uma conta, cada Utilizador aceita expressamente a versão em vigor dos presentes Termos. Data e versão da aceitação são registadas no servidor. A utilização continuada após alteração implica aceitação (art. 22).

## 3. Identificação do editor

O Serviço é operado pela **CARDELLI HERMANOS LIMITED** (n.º 2671528), sede social em Flat/RM A 12/F ZJ 300, 300 Lockhart Road, Wan Chai, Hong Kong. Contacto: **hopetsit@gmail.com**.

## 4. Objeto — exclusão de responsabilidade

A HopeTSIT é **exclusivamente um intermediário técnico de contacto**. A CARDELLI HERMANOS LIMITED **NÃO** é parte do contrato entre Petowners e Petsitters. A CARDELLI HERMANOS LIMITED **NÃO** é responsável, em nenhuma circunstância, por danos, acidentes, perdas, doenças ou morte de animais durante a prestação, nem por danos materiais ou pessoais.

## 5. Registo

Requer email válido, palavra-passe segura e aceitação dos presentes Termos. As contas são pessoais e intransmissíveis.

## 6. Obrigações do Petowner

Prestar informações exatas sobre saúde e vacinação; manter vacinas atualizadas e indicar veterinário contactável; subscrever, a seu critério, seguro de responsabilidade civil privada; realizar inventário foto/vídeo na entrega e devolução (recomendado); pagar o valor acordado pela Plataforma; respeitar as regras de cancelamento (art. 11).

## 7. Obrigações do Petsitter

Prestar informações verídicas sobre experiência, disponibilidade e localização; submeter documento de identidade para verificação antes do primeiro pagamento; tomar todas as precauções razoáveis para o bem-estar do animal; informar o Petowner sem demora de qualquer incidente; cumprir a descrição do serviço e o calendário acordado.

## 8. Seguros

A subscrição de qualquer seguro compete exclusivamente aos Utilizadores. A CARDELLI HERMANOS LIMITED recomenda vivamente um seguro RC privado. A CARDELLI HERMANOS LIMITED não oferece qualquer cobertura.

## 9. Reserva e aceitação mútua

Uma reserva torna-se firme apenas após (i) aceitação por ambas as partes e (ii) confirmação do pagamento. Antes do pagamento, qualquer parte pode retratar-se sem custos. Após o pagamento aplicam-se as regras de cancelamento (art. 11).

## 10. Pagamento

Os pagamentos são processados pela **Airwallex** (certificado PCI-DSS Nível 1). A HoPetSit nunca acede aos dados de cartão. A comissão da plataforma é de **vinte por cento (20 %)** do montante bruto da Reserva. Os fundos ficam retidos pela Airwallex até **24 horas após o fim do serviço**, sendo então **80 %** libertados para o IBAN do Petsitter e **20 %** retidos como comissão de plataforma.

## 11. Cancelamento e reembolso

- Mais de **72 horas** antes do serviço: **reembolso automático de 100 %** (auto-cancelamento na app).
- **72 horas ou menos** antes do serviço: o auto-cancelamento já não está disponível; é necessário um **cancelamento mútuo** com o Petsitter ou abrir um litígio formal via hopetsit@gmail.com — reembolsos avaliados caso a caso.
- Cancelamento pelo Petsitter: **reembolso integral de 100 %** ao Petowner.
- No-show do Petsitter: **reembolso integral** + sanção ao prestador.
- Após o início do serviço: sem reembolso, salvo resolução favorável de litígio.

Reembolsos via Airwallex para o cartão original em 5-10 dias úteis. Política de Reembolso completa em https://hopetsit.com/refund.

## 12. Chat

O chat é desbloqueado **apenas após confirmação do pagamento**. Partilhar emails é **proibido**; partilhar um número de telefone é permitido após pagamento.

## 13. Fidelidade e indicações

Os Petowners que completem 10 reservas obtêm o estatuto "Premium". Cada 3 reservas concluídas um crédito de -10 %. O programa de indicações concede 5 € na 1.ª reserva concluída do indicado. Créditos intransmissíveis, não reembolsáveis em dinheiro, não cumuláveis, validade 12 meses.

## 14. Propriedade intelectual

Todos os conteúdos publicados pela HopeTSIT são propriedade exclusiva da CARDELLI HERMANOS LIMITED. Os Utilizadores mantêm direitos sobre os seus conteúdos mas concedem à HopeTSIT uma licença mundial, gratuita e não exclusiva.

## 15. Dados pessoais (RGPD)

A HoPetSit é responsável pelo tratamento. Base legal: execução do contrato e, quando aplicável, consentimento. Conservação: duração da conta + 3 anos para faturação. Subcontratantes: Airwallex (pagamentos — PCI-DSS Nível 1), Firebase, Cloudinary, MongoDB Atlas, Google Maps. Direitos de acesso, retificação, apagamento, portabilidade e oposição: **hopetsit@gmail.com**.

## 16. Cookies

A aplicação usa armazenamento local e eventos estritamente necessários. Sem rastreadores publicitários sem consentimento explícito.

## 17. Moderação

A HopeTSIT pode moderar conteúdos, ocultar avaliações impróprias, suspender ou banir contas. Três denúncias ativam alerta interno.

## 18. Cessação

O Utilizador pode eliminar a conta a qualquer momento. Reservas pendentes devem ser primeiro resolvidas. Dados eliminados em 30 dias, salvo obrigação legal.

## 19. Responsabilidade limitada

Nos limites da lei, exclui-se a responsabilidade por danos indiretos, lucros cessantes, perda de dados ou prejuízo comercial. Responsabilidade máxima limitada ao valor da última transação.

## 20. Lei aplicável

Rege-se pela **lei da RAE de Hong Kong**, sem prejuízo das normas imperativas de proteção do consumidor do país de residência. Litígios submetidos ao **HKIAC** ou, à escolha do consumidor UE, aos tribunais competentes do país de residência.

## 21. Apoio ao cliente

**hopetsit@gmail.com**. Primeira resposta em 5 dias úteis.

## 22. Alteração

**30 dias** de pré-aviso antes da entrada em vigor. Utilização continuada implica aceitação.
""";

const Map<String, String> termsOfServiceByLocale = <String, String>{
  'en': _aiDisclaimerEn + _termsEn,
  'fr': _aiDisclaimerFr + _termsFr,
  'es': _aiDisclaimerEs + _termsEs,
  'de': _aiDisclaimerDe + _termsDe,
  'it': _aiDisclaimerIt + _termsIt,
  'pt': _aiDisclaimerPt + _termsPt,
};

String termsOfServiceForLocale(String languageCode) {
  final code = languageCode.toLowerCase();
  return termsOfServiceByLocale[code] ?? termsOfServiceByLocale['en']!;
}
