const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'PetsInsta Backend API',
      version: '1.0.0',
      description: 'Comprehensive API documentation for PetsInsta Backend - A pet care service platform connecting pet owners with pet sitters.',
      contact: {
        name: 'API Support',
        email: 'support@petsinsta.com',
      },
    },
    servers: [
      {
        url: 'http://localhost:5000',
        description: 'Development server',
      },
      {
        url: 'https://petinsta-backend-g7jn.onrender.com',
        description: 'Production server (Render)',
      },
      {
        url: 'https://api.petsinsta.com',
        description: 'Production server (Alternative)',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT token obtained from login endpoint. Format: Bearer <token>',
        },
      },
      schemas: {
        Notification: {
          type: 'object',
          properties: {
            id: { type: 'string', description: 'Notification id' },
            recipientRole: { type: 'string', enum: ['owner', 'sitter'] },
            recipientId: { type: 'string' },
            actorRole: { type: 'string', nullable: true, enum: ['owner', 'sitter'] },
            actorId: { type: 'string', nullable: true },
            type: {
              type: 'string',
              enum: [
                'post_like',
                'post_comment',
                'message_new',
                'application_new',
                'application_accepted',
                'application_rejected',
                'booking_new',
                'booking_accepted',
                'booking_rejected',
                'booking_paid',
              ],
            },
            title: { type: 'string' },
            body: { type: 'string' },
            data: { type: 'object', additionalProperties: true },
            readAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Error: {
          type: 'object',
          properties: {
            error: {
              type: 'string',
              description: 'Error message',
            },
          },
        },
        LocationResponse: {
          type: 'object',
          description: 'Location in API response format',
          properties: {
            lat: { type: 'number', description: 'Latitude' },
            lng: { type: 'number', description: 'Longitude' },
            city: { type: 'string', description: 'City name' },
            coordinates: {
              type: 'array',
              items: { type: 'number' },
              description: 'GeoJSON [longitude, latitude]',
            },
            locationType: {
              type: 'string',
              enum: ['standard', 'large_city'],
              description: 'Sitter only - area type',
            },
          },
        },
        Owner: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            email: { type: 'string' },
            mobile: { type: 'string' },
            countryCode: {
              type: 'string',
              description: 'International country calling code (E.164 format, e.g. +1, +44).',
              example: '+1',
            },
            address: { type: 'string' },
            location: {
              $ref: '#/components/schemas/LocationResponse',
            },
            language: { type: 'string' },
            currency: {
              type: 'string',
              description: 'Preferred currency (EUR or USD)',
              enum: ['EUR', 'USD'],
              example: 'EUR',
            },
            service: { type: 'array', items: { type: 'string' }, description: 'Service types' },
            avatar: {
              type: 'object',
              properties: {
                url: { type: 'string' },
                publicId: { type: 'string' },
              },
            },
            verified: { type: 'boolean' },
            authProvider: {
              type: 'string',
              description: 'Primary authentication provider for this account.',
              enum: ['password', 'google', 'apple'],
              example: 'google',
            },
            firebaseUid: {
              type: 'string',
              description: 'Firebase Authentication UID linked to this user (if any).',
              example: '4F2xYAbCdEfGhIjKlMnOpQrStUvWxYz1',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Sitter: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            email: { type: 'string' },
            mobile: { type: 'string' },
            paypalEmail: {
              type: 'string',
              format: 'email',
              description: 'PayPal payout email address for this sitter (optional).',
              example: 'sitter-payments@example.com',
            },
            countryCode: {
              type: 'string',
              description: 'International country calling code (E.164 format, e.g. +1, +44).',
              example: '+44',
            },
            address: { type: 'string' },
            location: {
              $ref: '#/components/schemas/LocationResponse',
            },
            language: { type: 'string' },
            currency: {
              type: 'string',
              description: 'Preferred currency (EUR or USD)',
              enum: ['EUR', 'USD'],
              example: 'EUR',
            },
            service: { type: 'array', items: { type: 'string' }, description: 'Service types' },
            bio: { type: 'string' },
            skills: { type: 'string' },
            hourlyRate: { type: 'number' },
            weeklyRate: { type: 'number' },
            monthlyRate: { type: 'number' },
            rating: { type: 'number' },
            reviewsCount: { type: 'number' },
            avatar: {
              type: 'object',
              properties: {
                url: { type: 'string' },
                publicId: { type: 'string' },
              },
            },
            verified: { type: 'boolean' },
            authProvider: {
              type: 'string',
              description: 'Primary authentication provider for this account.',
              enum: ['password', 'google', 'apple'],
              example: 'password',
            },
            firebaseUid: {
              type: 'string',
              description: 'Firebase Authentication UID linked to this user (if any).',
              example: '4F2xYAbCdEfGhIjKlMnOpQrStUvWxYz1',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Pet: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string' },
            petName: { type: 'string' },
            petType: { type: 'string' },
            breed: { type: 'string' },
            age: { type: 'number' },
            weight: { type: 'number' },
            height: { type: 'number' },
            colour: { type: 'string' },
            gender: { type: 'string' },
            description: { type: 'string' },
            avatar: {
              type: 'object',
              properties: {
                url: { type: 'string' },
                publicId: { type: 'string' },
              },
            },
            photos: { type: 'array', items: { type: 'object' } },
            passportImage: {
              type: 'object',
              properties: {
                url: { type: 'string' },
                publicId: { type: 'string' },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Booking: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string' },
            sitterId: { type: 'string' },
            petIds: { type: 'array', items: { type: 'string' } },
            description: { type: 'string' },
            date: { type: 'string' },
            startDate: { type: 'string', nullable: true },
            endDate: { type: 'string', nullable: true },
            timeSlot: { type: 'string' },
            serviceType: {
              nullable: true,
              oneOf: [{ type: 'string' }, { type: 'number' }, { type: 'boolean' }, { type: 'object' }],
            },
            houseSittingVenue: { type: 'string', nullable: true, enum: ['owners_home', 'sitters_home'] },
            duration: { type: 'number' },
            status: {
              type: 'string',
              enum: ['pending', 'accepted', 'rejected', 'agreed', 'paid', 'payment_failed', 'cancelled', 'refunded'],
            },
            paymentStatus: { type: 'string', enum: ['pending', 'paid', 'cancelled', 'refund'] },
            payoutStatus: { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'] },
            paypalOrderId: { type: 'string', nullable: true },
            paypalCaptureId: { type: 'string', nullable: true },
            payoutBatchId: { type: 'string', nullable: true },
            payoutId: { type: 'string', nullable: true },
            payoutAt: { type: 'string', format: 'date-time', nullable: true },
            pricing: {
              type: 'object',
              properties: {
                basePrice: { type: 'number' },
                pricingTier: { type: 'string', enum: ['hourly', 'weekly', 'monthly'] },
                appliedRate: { type: 'number' },
                totalHours: { type: 'number' },
                totalDays: { type: 'number' },
                addOns: { type: 'array', items: { type: 'object' } },
                addOnsTotal: { type: 'number' },
                totalPrice: { type: 'number' },
                commission: { type: 'number' },
                netPayout: { type: 'number' },
                commissionRate: { type: 'number' },
                currency: { type: 'string', enum: ['EUR', 'USD'] },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Application: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string', description: 'Owner ID (or populated owner object in responses)' },
            sitterId: { type: 'string', description: 'Sitter ID (or populated sitter object in responses)' },
            bookingId: { type: 'string', nullable: true, description: 'Linked Booking ID when accepted' },
            status: { type: 'string', enum: ['pending', 'accepted', 'rejected'] },
            petName: { type: 'string' },
            petIds: { type: 'array', items: { type: 'string' } },
            description: { type: 'string' },
            serviceDate: { type: 'string', format: 'date-time', nullable: true },
            startDate: { type: 'string', format: 'date-time', nullable: true },
            endDate: { type: 'string', format: 'date-time', nullable: true },
            timeSlot: { type: 'string' },
            serviceType: {
              nullable: true,
              oneOf: [{ type: 'string' }, { type: 'number' }, { type: 'boolean' }, { type: 'object' }],
            },
            houseSittingVenue: { type: 'string', nullable: true, enum: ['owners_home', 'sitters_home'] },
            duration: { type: 'number', nullable: true },
            locationType: { type: 'string', enum: ['standard', 'large_city'] },
            pricing: {
              type: 'object',
              properties: {
                basePrice: { type: 'number', nullable: true },
                pricingTier: { type: 'string', enum: ['hourly', 'weekly', 'monthly'] },
                appliedRate: { type: 'number' },
                totalHours: { type: 'number' },
                totalDays: { type: 'number' },
                addOns: { type: 'array', items: { type: 'object' } },
                addOnsTotal: { type: 'number' },
                totalPrice: { type: 'number', nullable: true },
                commission: { type: 'number', nullable: true },
                netPayout: { type: 'number', nullable: true },
                commissionRate: { type: 'number' },
                currency: { type: 'string', enum: ['EUR', 'USD'] },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Conversation: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string' },
            sitterId: { type: 'string' },
            lastMessage: { type: 'string' },
            lastMessageAt: { type: 'string', format: 'date-time' },
            ownerUnreadCount: { type: 'number' },
            sitterUnreadCount: { type: 'number' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Message: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            conversationId: { type: 'string' },
            senderRole: { type: 'string', enum: ['owner', 'sitter'] },
            senderId: { type: 'string' },
            body: { type: 'string' },
            attachments: { type: 'array', items: { type: 'object' } },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Post: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string' },
            postType: { type: 'string', enum: ['media', 'request'] },
            body: { type: 'string' },
            startDate: { type: 'string', format: 'date-time', nullable: true },
            endDate: { type: 'string', format: 'date-time', nullable: true },
            serviceTypes: { type: 'array', items: { type: 'string' } },
            houseSittingVenue: { type: 'string', nullable: true, enum: ['owners_home', 'sitters_home'] },
            images: { type: 'array', items: { type: 'object' } },
            videos: { type: 'array', items: { type: 'object' } },
            likes: { type: 'array', items: { type: 'string' } },
            comments: { type: 'array', items: { type: 'object' } },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Review: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string' },
            sitterId: { type: 'string' },
            bookingId: { type: 'string' },
            rating: { type: 'number', minimum: 1, maximum: 5 },
            comment: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        NearbySitter: {
          type: 'object',
          description: 'Sitter information with distance from search location',
          required:
            ['id', 'name', 'rating', 'reviewsCount', 'service', 'skills', 'hourlyRate', 'location', 'distance', 'verified'],
          properties: {
            id: {
              type: 'string',
              description: 'Unique sitter identifier',
              example: '507f1f77bcf86cd799439011',
            },
            name: {
              type: 'string',
              description: 'Full name of the sitter',
              example: 'Alex Petlover',
            },
            avatar: {
              type: 'object',
              description: 'Sitter profile picture/avatar',
              properties: {
                url: {
                  type: 'string',
                  format: 'uri',
                  description: 'URL of the avatar image',
                  example: 'https://res.cloudinary.com/example/image/upload/avatar.jpg',
                },
                publicId: {
                  type: 'string',
                  description: 'Cloudinary public ID for the avatar',
                  example: 'avatars/alex-petlover',
                },
              },
            },
            rating: {
              type: 'number',
              format: 'float',
              minimum: 0,
              maximum: 5,
              description: 'Average rating from reviews (0-5 scale)',
              example: 4.8,
            },
            reviewsCount: {
              type: 'integer',
              minimum: 0,
              description: 'Total number of reviews received',
              example: 25,
            },
            service: {
              type: 'array',
              items: { type: 'string' },
              description: 'Service types offered by the sitter',
              example: ['Dog Walking', 'Pet Sitting'],
            },
            skills: {
              type: 'array',
              description: 'Array of skills and specializations',
              items: {
                type: 'string',
              },
              example: ['Dog training', 'Cat care', 'Pet first aid'],
            },
            hourlyRate: {
              type: 'number',
              format: 'float',
              minimum: 0,
              description: 'Hourly rate charged by the sitter',
              example: 25,
            },
            weeklyRate: {
              type: 'number',
              format: 'float',
              minimum: 0,
              description: 'Weekly rate charged by the sitter',
              example: 700,
            },
            monthlyRate: {
              type: 'number',
              format: 'float',
              minimum: 0,
              description: 'Monthly rate charged by the sitter',
              example: 2600,
            },
            bio: {
              type: 'string',
              description: 'Brief biography or description of the sitter',
              example: 'Experienced pet sitter with 5 years of experience',
            },
            location: {
              type: 'object',
              description: 'Geographic location of the sitter',
              required: ['coordinates', 'city'],
              properties: {
                coordinates: {
                  type: 'array',
                  description: 'GeoJSON coordinates [longitude, latitude]',
                  items: {
                    type: 'number',
                  },
                  minItems: 2,
                  maxItems: 2,
                  example: [13.4050, 52.5200],
                },
                city: {
                  type: 'string',
                  description: 'City name where the sitter is located',
                  example: 'Berlin',
                },
              },
            },
            distance: {
              type: 'string',
              description: 'Distance from search location in kilometers (formatted to 2 decimal places)',
              example: '2.35',
            },
            distanceInMeters: {
              type: 'number',
              description: 'Distance from search location in meters (exact value)',
              example: 2350,
            },
            verified: {
              type: 'boolean',
              description: 'Whether the sitter account is verified',
              example: true,
            },
          },
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: ['./src/routes/*.js', './src/controllers/*.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;

